trigger:
- feature/*

pr:
- feature/*

resources:
- repo: self

variables:
  vmImageName: 'ubuntu-latest'

stages:
- stage: SonarCloudAnalysis
  displayName: SonarCloud Analysis Stage

  jobs:
  - job: Analyze
    displayName: Run SonarCloud Analysis

    pool:
      vmImage: $(vmImageName)

    steps:
    - checkout: self
      fetchDepth: 0

    - task: JavaToolInstaller@0
      displayName: 'Use Java 21 for SonarScanner'
      inputs:
        versionSpec: '21'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - task: SonarCloudPrepare@4 # NOSONAR
      displayName: 'Prepare SonarCloud Analysis'
      inputs:
        SonarCloud: 'sdk_sonar'
        organization: 'fastpix'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'FastPix_php-language-sdk-server-side'
        cliProjectName: 'php-language-sdk-server-side'
        extraProperties: |
          sonar.projectKey=FastPix_php-language-sdk-server-side
          sonar.organization=fastpix
          sonar.projectName=php-language-sdk-server-side
          sonar.sourceEncoding=UTF-8
          sonar.sources=.
          sonar.exclusions=src/*.php,src/Models/**,src/Utils/**
          sonar.issue.ignore.multicriteria=g1
          sonar.issue.ignore.multicriteria.g1.ruleKey=php:S1448
          sonar.issue.ignore.multicriteria.g1.resourceKey=src/Serializer/SerializerBuilder.php

    - task: SonarCloudAnalyze@4 #NOSONAR
      displayName: 'Run SonarCloud Code Analysis'

    - task: SonarCloudPublish@4 #NOSONAR
      displayName: 'Publish SonarCloud Quality Gate Results'
      inputs:
        pollingTimeoutSec: '300'