<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Errors;

class BadRequestExceptionThrowable extends \RuntimeException
{
    public BadRequestException $container;

    public function __construct(string $message, int $statusCode, BadRequestException $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}