<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Errors;


class Field
{
    /**
     * Displays the specific field associated with the error.
     *
     * @var ?string $field
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('field')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $field = null;

    /**
     * A descriptive message providing more details for the error
     *
     * @var ?string $message
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('message')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $message = null;

    /**
     * @param  ?string  $field
     * @param  ?string  $message
     * @phpstan-pure
     */
    public function __construct(?string $field = null, ?string $message = null)
    {
        $this->field = $field;
        $this->message = $message;
    }
}