<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Errors;

use FastPix\Sdk\Utils;
class UnauthorizedException
{
    /**
     * Demonstrates whether the request is successful or not.
     *
     * @var ?bool $success
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('success')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $success = null;

    /**
     * Displays details about the reasons behind the request's failure.
     *
     * @var ?UnauthorizedError $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\Type('\FastPix\Sdk\Models\Errors\UnauthorizedError|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UnauthorizedError $error = null;

    /**
     * @param  ?bool  $success
     * @param  ?UnauthorizedError  $error
     * @phpstan-pure
     */
    public function __construct(?bool $success = null, ?UnauthorizedError $error = null)
    {
        $this->success = $success;
        $this->error = $error;
    }

    public function toException(): UnauthorizedExceptionThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = -1;

        return new UnauthorizedExceptionThrowable($message, (int) $code, $this);
    }
}