<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */


declare(strict_types=1);

namespace FastPix\Sdk\Hooks;
use Psr\Http\Message\ResponseInterface;

class ErrorResponseContext
{
    public ?ResponseInterface $response;
    public ?\Throwable $e;

    public function __construct(?ResponseInterface $response, ?\Throwable $e)
    {
        $this->response = $response;
        $this->e = $e;
    }
}
