<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */


declare(strict_types=1);

namespace FastPix\Sdk\Hooks;

class TokenResponse
{
    public ?string $accessToken;
    public ?string $tokenType;
    public ?int $expiresIn;
}
