<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Utils\SdkMetadata;
class CancelUploadRequest
{
    /**
     * When uploading the media, FastPix assigns a universally unique identifier with a maximum length of 255 characters.
     *
     * @var string $uploadId
     */
    #[SdkMetadata('pathParam:style=simple,explode=false,name=uploadId')]
    public string $uploadId;

    /**
     * @param  string  $uploadId
     * @phpstan-pure
     */
    public function __construct(string $uploadId)
    {
        $this->uploadId = $uploadId;
    }
}