<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Models\Components;
/** CreateMediaPlaybackIdRequestBody - Request body for creating playback id for an media */
class CreateMediaPlaybackIdRequestBody
{
    /**
     * Access policy for media content
     *
     * @var Components\AccessPolicy $accessPolicy
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('accessPolicy')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\AccessPolicy')]
    public Components\AccessPolicy $accessPolicy;

    /**
     *
     * @var ?CreateMediaPlaybackIdAccessRestrictions $accessRestrictions
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('accessRestrictions')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Operations\CreateMediaPlaybackIdAccessRestrictions|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?CreateMediaPlaybackIdAccessRestrictions $accessRestrictions = null;

    /**
     * DRM configuration ID (required if accessPolicy is "drm")
     *
     * @var ?string $drmConfigurationId
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('drmConfigurationId')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $drmConfigurationId = null;

    /**
     * The maximum resolution for the playback ID.
     *
     * @var ?Resolution $resolution
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('resolution')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Operations\Resolution|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?Resolution $resolution = null;

    /**
     * @param  Components\AccessPolicy  $accessPolicy
     * @param  ?CreateMediaPlaybackIdAccessRestrictions  $accessRestrictions
     * @param  ?string  $drmConfigurationId
     * @param  ?Resolution  $resolution
     * @phpstan-pure
     */
    public function __construct(Components\AccessPolicy $accessPolicy, ?CreateMediaPlaybackIdAccessRestrictions $accessRestrictions = null, ?string $drmConfigurationId = null, ?Resolution $resolution = null)
    {
        $this->accessPolicy = $accessPolicy;
        $this->accessRestrictions = $accessRestrictions;
        $this->drmConfigurationId = $drmConfigurationId;
        $this->resolution = $resolution;
    }
}
