<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;


/** CreateMediaPlaybackIdRequestBody - Request body for creating playback id for an media */
class CreateMediaPlaybackIdRequestBody
{
    /**
     * Determines if access to the streamed content is kept private or available to all.
     *
     * @var CreateMediaPlaybackIdAccessPolicy $accessPolicy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accessPolicy')]
    #[\Speakeasy\Serializer\Annotation\Type('\FastPix\Sdk\Models\Operations\CreateMediaPlaybackIdAccessPolicy')]
    public CreateMediaPlaybackIdAccessPolicy $accessPolicy;

    /**
     *
     * @var ?CreateMediaPlaybackIdAccessRestrictions $accessRestrictions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accessRestrictions')]
    #[\Speakeasy\Serializer\Annotation\Type('\FastPix\Sdk\Models\Operations\CreateMediaPlaybackIdAccessRestrictions|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateMediaPlaybackIdAccessRestrictions $accessRestrictions = null;

    /**
     * @param  CreateMediaPlaybackIdAccessPolicy  $accessPolicy
     * @param  ?CreateMediaPlaybackIdAccessRestrictions  $accessRestrictions
     * @phpstan-pure
     */
    public function __construct(CreateMediaPlaybackIdAccessPolicy $accessPolicy, ?CreateMediaPlaybackIdAccessRestrictions $accessRestrictions = null)
    {
        $this->accessPolicy = $accessPolicy;
        $this->accessRestrictions = $accessRestrictions;
    }
}