<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;


class CreateMediaPlaybackIdAccessRestrictions
{
    /**
     *
     * @var ?CreateMediaPlaybackIdDomains $domains
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('domains')]
    #[\Speakeasy\Serializer\Annotation\Type('\FastPix\Sdk\Models\Operations\CreateMediaPlaybackIdDomains|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateMediaPlaybackIdDomains $domains = null;

    /**
     *
     * @var ?CreateMediaPlaybackIdUserAgents $userAgents
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('userAgents')]
    #[\Speakeasy\Serializer\Annotation\Type('\FastPix\Sdk\Models\Operations\CreateMediaPlaybackIdUserAgents|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateMediaPlaybackIdUserAgents $userAgents = null;

    /**
     * @param  ?CreateMediaPlaybackIdDomains  $domains
     * @param  ?CreateMediaPlaybackIdUserAgents  $userAgents
     * @phpstan-pure
     */
    public function __construct(?CreateMediaPlaybackIdDomains $domains = null, ?CreateMediaPlaybackIdUserAgents $userAgents = null)
    {
        $this->domains = $domains;
        $this->userAgents = $userAgents;
    }
}