<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Models\Components;
/** CreateMediaResponseBody - Media is created successfully */
class CreateMediaResponseBody
{
    /**
     * Demonstrates whether the request is successful or not.
     *
     * @var ?bool $success
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('success')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $success = null;

    /**
     *
     * @var ?Components\CreateMediaResponse $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\CreateMediaResponse|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Components\CreateMediaResponse $data = null;

    /**
     * @param  ?bool  $success
     * @param  ?Components\CreateMediaResponse  $data
     * @phpstan-pure
     */
    public function __construct(?bool $success = null, ?Components\CreateMediaResponse $data = null)
    {
        $this->success = $success;
        $this->data = $data;
    }
}