<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;


/** DeleteMediaResponseBody - Delete a video media */
class DeleteMediaResponseBody
{
    /**
     * Demonstrates whether the request is successful or not.
     *
     * @var ?bool $success
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('success')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $success = null;

    /**
     * @param  ?bool  $success
     * @phpstan-pure
     */
    public function __construct(?bool $success = null)
    {
        $this->success = $success;
    }
}
