<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Utils\SpeakeasyMetadata;
class DeleteLiveStreamRequest
{
    /**
     * Upon creating a new live stream, FastPix assigns a unique identifier to the stream.
     *
     * @var string $streamId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=streamId')]
    public string $streamId;

    /**
     * @param  string  $streamId
     * @phpstan-pure
     */
    public function __construct(string $streamId)
    {
        $this->streamId = $streamId;
    }
}