<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Utils\SdkMetadata;
class DeleteSigningKeyRequest
{
    /**
     * When creating the signing key, FastPix assigns a universally unique identifier with a maximum length of 255 characters.
     *
     * @var string $signingKeyId
     */
    #[SdkMetadata('pathParam:style=simple,explode=false,name=signingKeyId')]
    public string $signingKeyId;

    /**
     * @param  string  $signingKeyId
     * @phpstan-pure
     */
    public function __construct(string $signingKeyId)
    {
        $this->signingKeyId = $signingKeyId;
    }
}
