<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;


/** DirectUploadVideoMediaRequest - Request body for direct upload */
class DirectUploadVideoMediaRequest
{
    /**
     * Configuration settings for uploading and processing media on the FastPix platform.  
     *
     * These settings define how the uploaded video is handled, including access control, resolution, DRM, and optional metadata.  
     * For a complete explanation of how media uploads and processing work, refer to the  
     * <a href="https://docs.fastpix.io/docs/video-on-demand-overview" target="_blank">FastPix Video on Demand Overview</a>.
     *
     *
     * @var ?PushMediaSettings $pushMediaSettings
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('pushMediaSettings')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Operations\PushMediaSettings|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?PushMediaSettings $pushMediaSettings = null;

    /**
     * Upload media directly from a device using the URL name or enter "*" to allow all.
     *
     * @var ?string $corsOrigin
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('corsOrigin')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $corsOrigin = null;

    /**
     * @param  ?string  $corsOrigin
     * @param  ?PushMediaSettings  $pushMediaSettings
     * @phpstan-pure
     */
    public function __construct(?PushMediaSettings $pushMediaSettings = null, ?string $corsOrigin = '*')
    {
        $this->pushMediaSettings = $pushMediaSettings;
        $this->corsOrigin = $corsOrigin;
    }
}