<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;


/** DirectUploadVideoMediaRequest - Request body for direct upload */
class DirectUploadVideoMediaRequest
{
    /**
     * Upload media directly from a device using the URL name or enter '*' to allow all.
     *
     * @var string $corsOrigin
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('corsOrigin')]
    public string $corsOrigin;

    /**
     * Configuration settings for media upload.
     *
     * @var ?PushMediaSettings $pushMediaSettings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pushMediaSettings')]
    #[\Speakeasy\Serializer\Annotation\Type('\FastPix\Sdk\Models\Operations\PushMediaSettings|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PushMediaSettings $pushMediaSettings = null;

    /**
     * @param  string  $corsOrigin
     * @param  ?PushMediaSettings  $pushMediaSettings
     * @phpstan-pure
     */
    public function __construct(string $corsOrigin, ?PushMediaSettings $pushMediaSettings = null)
    {
        $this->corsOrigin = $corsOrigin;
        $this->pushMediaSettings = $pushMediaSettings;
    }
}