<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Models\Components;
/** GenerateSubtitleTrackResponseBody - Media details updated successfully */
class GenerateSubtitleTrackResponseBody
{
    /**
     * Demonstrates whether the request is successful or not.
     *
     * @var ?bool $success
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('success')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $success = null;

    /**
     * Represents the response for a successfully generated subtitle track.
     *
     * @var ?Components\GenerateTrackResponse $data
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('data')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\GenerateTrackResponse|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?Components\GenerateTrackResponse $data = null;

    /**
     * @param  ?bool  $success
     * @param  ?Components\GenerateTrackResponse  $data
     * @phpstan-pure
     */
    public function __construct(?bool $success = null, ?Components\GenerateTrackResponse $data = null)
    {
        $this->success = $success;
        $this->data = $data;
    }
}