<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Utils\SpeakeasyMetadata;
class GetAllStreamsRequest
{
    /**
     * Limit specifies the maximum number of items to display per page.
     *
     * @var ?string $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?string $limit = null;

    /**
     * Offset determines the starting point for data retrieval within a paginated list.
     *
     * @var ?string $offset
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=offset')]
    public ?string $offset = null;

    /**
     * The list of value can be order in two ways DESC (Descending) or ASC (Ascending). In case not specified, by default it will be DESC.
     *
     * @var ?GetAllStreamsOrderBy $orderBy
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=orderBy')]
    public ?GetAllStreamsOrderBy $orderBy = null;

    /**
     * @param  ?string  $limit
     * @param  ?string  $offset
     * @param  ?GetAllStreamsOrderBy  $orderBy
     * @phpstan-pure
     */
    public function __construct(?string $limit = '10', ?string $offset = '1', ?GetAllStreamsOrderBy $orderBy = GetAllStreamsOrderBy::Desc)
    {
        $this->limit = $limit;
        $this->offset = $offset;
        $this->orderBy = $orderBy;
    }
}