<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;


/** GetMediaSummaryResponseBody - Get media summary */
class GetMediaSummaryResponseBody
{
    /**
     * Shows the request status. Returns true for success and false for failure.
     *
     * @var ?bool $success
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('success')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $success = null;

    /**
     * The summary of the particular video.
     *
     * @var ?string $data
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('data')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $data = null;

    /**
     * @param  ?bool  $success
     * @param  ?string  $data
     * @phpstan-pure
     */
    public function __construct(?bool $success = null, ?string $data = null)
    {
        $this->success = $success;
        $this->data = $data;
    }
}
