<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Models\Components;
/** GetMediaResponseBody - Get a video media by id */
class GetMediaResponseBody
{
    /**
     * Demonstrates whether the request is successful or not.
     *
     * @var ?bool $success
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('success')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $success = null;

    /**
     *
     * @var ?Components\GetMediaResponse $data
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('data')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\GetMediaResponse|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?Components\GetMediaResponse $data = null;

    /**
     * @param  ?bool  $success
     * @param  ?Components\GetMediaResponse  $data
     * @phpstan-pure
     */
    public function __construct(?bool $success = null, ?Components\GetMediaResponse $data = null)
    {
        $this->success = $success;
        $this->data = $data;
    }
}