<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Utils\SpeakeasyMetadata;
class GetMediaRequest
{
    /**
     * The Media Id is assigned a universal unique identifier, which can contain a maximum of 255 characters.
     *
     * @var string $mediaId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=mediaId')]
    public string $mediaId;

    /**
     * @param  string  $mediaId
     * @phpstan-pure
     */
    public function __construct(string $mediaId)
    {
        $this->mediaId = $mediaId;
    }
}