<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Utils\SdkMetadata;
class GetPlaybackIdRequest
{
    /**
     *
     * @var string $mediaId
     */
    #[SdkMetadata('pathParam:style=simple,explode=false,name=mediaId')]
    public string $mediaId;

    /**
     *
     * @var string $playbackId
     */
    #[SdkMetadata('pathParam:style=simple,explode=false,name=playbackId')]
    public string $playbackId;

    /**
     * @param  string  $mediaId
     * @param  string  $playbackId
     * @phpstan-pure
     */
    public function __construct(string $mediaId, string $playbackId)
    {
        $this->mediaId = $mediaId;
        $this->playbackId = $playbackId;
    }
}
