<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Models\Components;
/** GetVideoViewDetailsResponseBody - Get a video view by id */
class GetVideoViewDetailsResponseBody
{
    /**
     * Shows the request status. Returns true for success and false for failure.
     *
     * @var ?bool $success
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('success')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $success = null;

    /**
     * Displays the result of the request.
     *
     * @var ?Components\Views $data
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('data')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\Views|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?Components\Views $data = null;

    /**
     * @param  ?bool  $success
     * @param  ?Components\Views  $data
     * @phpstan-pure
     */
    public function __construct(?bool $success = null, ?Components\Views $data = null)
    {
        $this->success = $success;
        $this->data = $data;
    }
}