<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Models\Components;
class GetVideoViewDetailsResponse
{
    /**
     * HTTP response content type for this operation
     *
     * @var string $contentType
     */
    public string $contentType;

    /**
     * HTTP response status code for this operation
     *
     * @var int $statusCode
     */
    public int $statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var \Psr\Http\Message\ResponseInterface $rawResponse
     */
    public \Psr\Http\Message\ResponseInterface $rawResponse;

    /**
     * Get a video view by id
     *
     * @var ?GetVideoViewDetailsResponseBody $object
     */
    public ?GetVideoViewDetailsResponseBody $object = null;

    /**
     * See the range of possible <a href="https://docs.fastpix.io/reference/error-codes">error</a> responses and their status codes.
     *
     * @var ?Components\DefaultError $defaultError
     */
    public ?Components\DefaultError $defaultError = null;

    /**
     * @param  string  $contentType
     * @param  int  $statusCode
     * @param  \Psr\Http\Message\ResponseInterface  $rawResponse
     * @param  ?GetVideoViewDetailsResponseBody  $object
     * @param  ?Components\DefaultError  $defaultError
     * @phpstan-pure
     */
    public function __construct(string $contentType, int $statusCode, \Psr\Http\Message\ResponseInterface $rawResponse, ?GetVideoViewDetailsResponseBody $object = null, ?Components\DefaultError $defaultError = null)
    {
        $this->contentType = $contentType;
        $this->statusCode = $statusCode;
        $this->rawResponse = $rawResponse;
        $this->object = $object;
        $this->defaultError = $defaultError;
    }
}