<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;


/**
 * Language codes (BCP 47 compliant) used for text files.
 *
 *
 */
enum LanguageCode: string
{
    case En = 'en';
    case It = 'it';
    case Pl = 'pl';
    case Es = 'es';
    case Fr = 'fr';
    case Ru = 'ru';
    case Nl = 'nl';
}
