<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Utils\SdkMetadata;
class ListSigningKeysRequest
{
    /**
     * Limit specifies the maximum number of items to display per page.
     *
     * @var ?int $limit
     */
    #[SdkMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;

    /**
     * It is used for pagination, indicating the starting point for fetching data.
     *
     * @var ?int $offset
     */
    #[SdkMetadata('queryParam:style=form,explode=true,name=offset')]
    public ?int $offset = null;

    /**
     * @param  ?int  $limit
     * @param  ?int  $offset
     * @phpstan-pure
     */
    public function __construct(?int $limit = 10, ?int $offset = 1)
    {
        $this->limit = $limit;
        $this->offset = $offset;
    }
}
