<?php



declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Utils\FastPixMetadata;
class ListVideoViewsRequest
{
    /**
     * This parameter specifies the time span between which the video views list should be retrieved by. You can provide either from and to unix epoch timestamps or time duration. The scope of duration is between 60 minutes to 30 days.
     *
     *
     *
     * @var ListVideoViewsTimespan $timespan
     */
    #[FastPixMetadata('queryParam:style=form,explode=true,name=timespan[]')]
    public ListVideoViewsTimespan $timespan;

    /**
     * Pass the dimensions and their corresponding values you want to filter the views by. For excluding the values in the filter we can pass '!' before the filter value. The list of filters can be obtained from list of dimensions endpoint.
     *
     * Example Values : [ browser_name:Chrome , os_name:macOS , device_name:Galaxy ]
     *
     *
     * @var ?string $filterby
     */
    #[FastPixMetadata('queryParam:style=form,explode=true,name=filterby[]')]
    public ?string $filterby = null;

    /**
     * Pass the viewer_id to filter the list of views. This value can be manually set during integration or generated by FastPix. When set manually it can be a string of aplha numeric values of any length.
     *
     *
     *
     * @var ?string $viewerId
     */
    #[FastPixMetadata('queryParam:style=form,explode=true,name=viewerId')]
    public ?string $viewerId = null;

    /**
     * Pass the error code to filter the list of views. The possible values of error code can be fetched from list of errors end point.
     *
     *
     *
     * @var string|int|null $errorCode
     */
    #[FastPixMetadata('queryParam:style=form,explode=true,name=errorCode')]
    public string|int|null $errorCode = null;

    /**
     * Pass the limit to display only the rows specified by the value.
     *
     *
     *
     * @var ?int $limit
     */
    #[FastPixMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;

    /**
     * Pass the offset value to indicate the page number.
     *
     *
     *
     * @var ?int $offset
     */
    #[FastPixMetadata('queryParam:style=form,explode=true,name=offset')]
    public ?int $offset = null;

    /**
     * Pass this value to sort the view list by.
     *
     *
     *
     * @var ?string $orderBy
     */
    #[FastPixMetadata('queryParam:style=form,explode=true,name=orderBy')]
    public ?string $orderBy = null;

    /**
     * The order direction to sort the view list by.
     *
     *
     *
     * @var ?string $sortOrder
     */
    #[FastPixMetadata('queryParam:style=form,explode=true,name=sortOrder')]
    public ?string $sortOrder = null;

    /**
     * @param  ListVideoViewsTimespan  $timespan
     * @param  ?string  $filterby
     * @param  ?int  $limit
     * @param  ?int  $offset
     * @param  ?string  $viewerId
     * @param  ?string  $orderBy
     * @param  ?string  $sortOrder
     * @param  string|int|null  $errorCode
     * @phpstan-pure
     */
    public function __construct(ListVideoViewsTimespan $timespan, ?string $filterby = null, ?string $viewerId = null, string|int|null $errorCode = null, ?int $limit = 10, ?int $offset = 1, ?string $orderBy = 'view_end', ?string $sortOrder = 'asc')
    {
        $this->timespan = $timespan;
        $this->filterby = $filterby;
        $this->viewerId = $viewerId;
        $this->errorCode = $errorCode;
        $this->limit = $limit;
        $this->offset = $offset;
        $this->orderBy = $orderBy;
        $this->sortOrder = $sortOrder;
    }
}