<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;


class ListPlaybackIdsData
{
    /**
     * Unique identifier of the playback ID.
     *
     * @var ?string $id
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('id')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * The access policy set for the playback ID.
     *
     * @var ?ListPlaybackIdsAccessPolicy $accessPolicy
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('accessPolicy')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Operations\ListPlaybackIdsAccessPolicy|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?ListPlaybackIdsAccessPolicy $accessPolicy = null;

    /**
     * Restrictions applied to this playback ID.
     *
     * @var ?ListPlaybackIdsAccessRestrictions $accessRestrictions
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('accessRestrictions')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Operations\ListPlaybackIdsAccessRestrictions|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?ListPlaybackIdsAccessRestrictions $accessRestrictions = null;

    /**
     * @param  ?string  $id
     * @param  ?ListPlaybackIdsAccessPolicy  $accessPolicy
     * @param  ?ListPlaybackIdsAccessRestrictions  $accessRestrictions
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?ListPlaybackIdsAccessPolicy $accessPolicy = null, ?ListPlaybackIdsAccessRestrictions $accessRestrictions = null)
    {
        $this->id = $id;
        $this->accessPolicy = $accessPolicy;
        $this->accessRestrictions = $accessRestrictions;
    }
}
