<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Utils\SdkMetadata;
class ListErrorsRequest
{
    /**
     * This parameter specifies the time span between which the video views list must be retrieved by. You can provide either from and to unix epoch timestamps or time duration. The scope of duration is between 60 minutes to 30 days.
     *
     *
     * **Accepted formats are:**
     *
     * array of epoch timestamps for example  
     * `timespan[]=1498867200&timespan[]=1498953600`
     *
     * duration string for example  
     * `timespan[]=24:hours` or `timespan[]=7:days`
     *
     *
     * @var ?ListErrorsTimespan $timespan
     */
    #[SdkMetadata('queryParam:style=form,explode=true,name=timespan[]')]
    public ?ListErrorsTimespan $timespan = null;

    /**
     * Pass the dimensions and their corresponding values you want to filter the views by. For excluding the values in the filter we can pass "!" before the filter value. The list of filters can be obtained from list of dimensions endpoint.
     *
     * Example Values : [ browser_name:Chrome , os_name:macOS , !device_name:Galaxy ]
     *
     *
     * @var ?string $filterby
     */
    #[SdkMetadata('queryParam:style=form,explode=true,name=filterby[]')]
    public ?string $filterby = null;

    /**
     * Pass the limit to display only the rows specified by the value for top errors.
     *
     *
     *
     * @var ?int $limit
     */
    #[SdkMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;

    /**
     * @param  ?ListErrorsTimespan  $timespan
     * @param  ?string  $filterby
     * @param  ?int  $limit
     * @phpstan-pure
     */
    public function __construct(?ListErrorsTimespan $timespan = null, ?string $filterby = null, ?int $limit = 1)
    {
        $this->timespan = $timespan;
        $this->filterby = $filterby;
        $this->limit = $limit;
    }
}