<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Utils\SpeakeasyMetadata;
class ListMediaRequest
{
    /**
     * Limit specifies the maximum number of items to display per page.
     *
     * @var ?int $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?int $limit = null;

    /**
     * Offset determines the starting point for data retrieval within a paginated list.
     *
     * @var ?int $offset
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=offset')]
    public ?int $offset = null;

    /**
     * The values in the list can be arranged in two ways: DESC (Descending) or ASC (Ascending).
     *
     * @var ?ListMediaOrderBy $orderBy
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=orderBy')]
    public ?ListMediaOrderBy $orderBy = null;

    /**
     * @param  ?int  $limit
     * @param  ?int  $offset
     * @param  ?ListMediaOrderBy  $orderBy
     * @phpstan-pure
     */
    public function __construct(?int $limit = 10, ?int $offset = 1, ?ListMediaOrderBy $orderBy = ListMediaOrderBy::Desc)
    {
        $this->limit = $limit;
        $this->offset = $offset;
        $this->orderBy = $orderBy;
    }
}