<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Models\Components;
/**
 * PushMediaSettings - Configuration settings for uploading and processing media on the FastPix platform.  
 *
 * These settings define how the uploaded video is handled, including access control, resolution, DRM, and optional metadata.  
 * For a complete explanation of how media uploads and processing work, refer to the  
 * <a href="https://fastpix.com/docs/get-started/overview" target="_blank">FastPix Video on Demand Overview</a>.
 *
 */
class PushMediaSettings
{
    /**
     * Start time indicates where encoding must begin within the video file, in seconds.
     *
     * @var ?float $startTime
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('startTime')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?float $startTime = null;

    /**
     * End time indicates where encoding must end within the video file, in seconds.
     *
     * @var ?float $endTime
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('endTime')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?float $endTime = null;

    /**
     * Add one input object at a time. For example, first add a **WatermarkInput** object.   If you also need a audio, click **Add item** again and select **AudioInput**.   Repeat this process for **SubtitleInput** as needed.
     *
     *
     *
     * @var ?array<Components\VideoInput|Components\WatermarkInput|Components\AudioInput|Components\SubtitleInput> $inputs
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('inputs')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('array<\FastPix\Sdk\Models\Components\VideoInput|\FastPix\Sdk\Models\Components\WatermarkInput|\FastPix\Sdk\Models\Components\AudioInput|\FastPix\Sdk\Models\Components\SubtitleInput>|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?array $inputs = null;

    /**
     * "Tag a video in "key" : "value" pairs for searchable metadata. Maximum 10 entries, 255 characters each."
     *
     *
     *
     * @var ?array<string, string> $metadata
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('metadata')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('array<string, string>|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * UUID of the DRM configuration to be used.
     *
     * @var ?string $drmConfigurationId
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('drmConfigurationId')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $drmConfigurationId = null;

    /**
     * Title of the media file.
     *
     * @var ?string $title
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('title')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     * The unique identifier of the user who created this media.
     *
     * @var ?string $creatorId
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('creatorId')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $creatorId = null;

    /**
     * Generates subtitle files for audio/video files.
     *
     *
     *
     * @var ?Subtitles $subtitles
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('subtitles')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Operations\Subtitles|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?Subtitles $subtitles = null;

    /**
     * Enhance the quality and volume of the audio track. This is available for pre-recorded content only.
     *
     *
     *
     * @var ?bool $optimizeAudio
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('optimizeAudio')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $optimizeAudio = null;

    /**
     * The sourceAccess parameter determines whether the original media file is accessible. Set to true to enable access or false to restrict it
     *
     * @var ?bool $sourceAccess
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('sourceAccess')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $sourceAccess = null;

    /**
     * Generates MP4 video up to 4K ("capped_4k"), m4a audio only ("audioOnly"), or both for offline viewing.
     *
     *
     *
     * @var ?DirectUploadVideoMediaMp4Support $mp4Support
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('mp4Support')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Operations\DirectUploadVideoMediaMp4Support|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?DirectUploadVideoMediaMp4Support $mp4Support = null;

    /**
     *
     * @var ?Summary $summary
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('summary')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Operations\Summary|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?Summary $summary = null;

    /**
     * Enable or disable the chapters feature for the media. Set to `true` to enable chapters or `false` to disable.
     *
     *
     *
     * @var ?bool $chapters
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('chapters')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $chapters = null;

    /**
     * Enable or disable named entity extraction. Set to `true` to enable or `false` to disable.
     *
     *
     *
     * @var ?bool $namedEntities
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('namedEntities')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $namedEntities = null;

    /**
     *
     * @var ?DirectUploadVideoMediaModeration $moderation
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('moderation')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Operations\DirectUploadVideoMediaModeration|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?DirectUploadVideoMediaModeration $moderation = null;

    /**
     *
     * @var ?DirectUploadVideoMediaAccessRestrictions $accessRestrictions
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('accessRestrictions')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Operations\DirectUploadVideoMediaAccessRestrictions|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?DirectUploadVideoMediaAccessRestrictions $accessRestrictions = null;

    /**
     * Determines if access to the streamed content is kept private, drm or available to all.
     *
     * @var ?DirectUploadVideoMediaAccessPolicy $accessPolicy
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('accessPolicy')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Operations\DirectUploadVideoMediaAccessPolicy|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?DirectUploadVideoMediaAccessPolicy $accessPolicy = null;

    /**
     * Determines the highest quality resolution available.
     *
     *
     *
     * @var ?MaxResolution $maxResolution
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('maxResolution')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Operations\MaxResolution|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?MaxResolution $maxResolution = null;

    /**
     * The quality tier applied to the media.
     *
     * @var ?MediaQuality $mediaQuality
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('mediaQuality')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Operations\MediaQuality|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?MediaQuality $mediaQuality = null;

    /**
     * @param  ?DirectUploadVideoMediaAccessPolicy  $accessPolicy
     * @param  ?float  $startTime
     * @param  ?float  $endTime
     * @param  ?array<Components\VideoInput|Components\WatermarkInput|Components\AudioInput|Components\SubtitleInput>  $inputs
     * @param  ?array<string, string>  $metadata
     * @param  ?string  $drmConfigurationId
     * @param  ?string  $title
     * @param  ?string  $creatorId
     * @param  ?Subtitles  $subtitles
     * @param  ?bool  $optimizeAudio
     * @param  ?MaxResolution  $maxResolution
     * @param  ?MediaQuality  $mediaQuality
     * @param  ?bool  $sourceAccess
     * @param  ?DirectUploadVideoMediaMp4Support  $mp4Support
     * @param  ?Summary  $summary
     * @param  ?bool  $chapters
     * @param  ?bool  $namedEntities
     * @param  ?DirectUploadVideoMediaModeration  $moderation
     * @param  ?DirectUploadVideoMediaAccessRestrictions  $accessRestrictions
     * @phpstan-pure
     */
    public function __construct(?float $startTime = null, ?float $endTime = null, ?array $inputs = null, ?array $metadata = null, ?string $drmConfigurationId = null, ?string $title = null, ?string $creatorId = null, ?Subtitles $subtitles = null, ?bool $optimizeAudio = null, ?bool $sourceAccess = null, ?DirectUploadVideoMediaMp4Support $mp4Support = null, ?Summary $summary = null, ?bool $chapters = null, ?bool $namedEntities = null, ?DirectUploadVideoMediaModeration $moderation = null, ?DirectUploadVideoMediaAccessRestrictions $accessRestrictions = null, ?DirectUploadVideoMediaAccessPolicy $accessPolicy = DirectUploadVideoMediaAccessPolicy::Public, ?MaxResolution $maxResolution = MaxResolution::OneThousandAndEightyp, ?MediaQuality $mediaQuality = MediaQuality::Standard)
    {
        $this->startTime = $startTime;
        $this->endTime = $endTime;
        $this->inputs = $inputs;
        $this->metadata = $metadata;
        $this->drmConfigurationId = $drmConfigurationId;
        $this->title = $title;
        $this->creatorId = $creatorId;
        $this->subtitles = $subtitles;
        $this->optimizeAudio = $optimizeAudio;
        $this->sourceAccess = $sourceAccess;
        $this->mp4Support = $mp4Support;
        $this->summary = $summary;
        $this->chapters = $chapters;
        $this->namedEntities = $namedEntities;
        $this->moderation = $moderation;
        $this->accessRestrictions = $accessRestrictions;
        $this->accessPolicy = $accessPolicy;
        $this->maxResolution = $maxResolution;
        $this->mediaQuality = $mediaQuality;
    }
}