<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;


/** RetrieveMediaInputInfoResponseBody - Get video media input information */
class RetrieveMediaInputInfoResponseBody
{
    /**
     * Shows the request status. Returns true for success and false for failure.
     *
     * @var ?bool $success
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('success')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $success = null;

    /**
     * Displays the result of the request.
     *
     * @var ?RetrieveMediaInputInfoData $data
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('data')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Operations\RetrieveMediaInputInfoData|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?RetrieveMediaInputInfoData $data = null;

    /**
     * @param  ?bool  $success
     * @param  ?RetrieveMediaInputInfoData  $data
     * @phpstan-pure
     */
    public function __construct(?bool $success = null, ?RetrieveMediaInputInfoData $data = null)
    {
        $this->success = $success;
        $this->data = $data;
    }
}