<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;


/** RetrieveMediaInputInfoResponseBody - Get video media input information */
class RetrieveMediaInputInfoResponseBody
{
    /**
     * Demonstrates whether the request is successful or not.
     *
     * @var ?bool $success
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('success')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $success = null;

    /**
     * Displays the result of the request.
     *
     * @var mixed $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public mixed $data = null;

    /**
     * @param  ?bool  $success
     * @param  mixed  $data
     * @phpstan-pure
     */
    public function __construct(?bool $success = null, mixed $data = null)
    {
        $this->success = $success;
        $this->data = $data;
    }
}