<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;


/**
 * Defines the type of input. Possible values include video, audio, av.
 *
 *
 */
enum Type: string
{
    case Video = 'video';
    case Audio = 'audio';
    case Av = 'av';
}
