<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Models\Components;
class UpdateMediaModerationModeration
{
    /**
     * Type of media content
     *
     * @var ?Components\MediaType $type
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('type')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\MediaType|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?Components\MediaType $type = null;

    /**
     * @param  ?Components\MediaType  $type
     * @phpstan-pure
     */
    public function __construct(?Components\MediaType $type = Components\MediaType::Audio)
    {
        $this->type = $type;
    }
}
