<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;


/** The default behavior when a user-agent is not listed in `allow` or `deny`. */
enum UpdateUserAgentRestrictionsDefaultPolicy: string
{
    case Allow = 'allow';
    case Deny = 'deny';
}
