<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Models\Components;
use FastPix\Sdk\Utils\SdkMetadata;
class UpdateAPlaylistRequest
{
    /**
     * The unique id of the playlist you want to retrieve.
     *
     * @var string $playlistId
     */
    #[SdkMetadata('pathParam:style=simple,explode=false,name=playlistId')]
    public string $playlistId;

    /**
     *
     * @var Components\UpdatePlaylistRequest $body
     */
    #[SdkMetadata('request:mediaType=application/json')]
    public Components\UpdatePlaylistRequest $body;

    /**
     * @param  string  $playlistId
     * @param  Components\UpdatePlaylistRequest  $body
     * @phpstan-pure
     */
    public function __construct(string $playlistId, Components\UpdatePlaylistRequest $body)
    {
        $this->playlistId = $playlistId;
        $this->body = $body;
    }
}