<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;


class UpdateLiveStreamDomainRestrictionsRequestBody
{
    /**
     * List of domains explicitly allowed to play the live stream.
     *
     * @var ?array<string> $allow
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('allow')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('array<string>|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?array $allow = null;

    /**
     * List of domains explicitly denied from accessing the live stream.
     *
     * @var ?array<string> $deny
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('deny')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('array<string>|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?array $deny = null;

    /**
     * Specify the fallback behavior for domains that are not listed in the `allow` or `deny` lists.
     *
     * @var ?UpdateLiveStreamDomainRestrictionsDefaultPolicy $defaultPolicy
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('defaultPolicy')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Operations\UpdateLiveStreamDomainRestrictionsDefaultPolicy|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?UpdateLiveStreamDomainRestrictionsDefaultPolicy $defaultPolicy = null;

    /**
     * @param  ?UpdateLiveStreamDomainRestrictionsDefaultPolicy  $defaultPolicy
     * @param  ?array<string>  $allow
     * @param  ?array<string>  $deny
     * @phpstan-pure
     */
    public function __construct(?array $allow = null, ?array $deny = null, ?UpdateLiveStreamDomainRestrictionsDefaultPolicy $defaultPolicy = UpdateLiveStreamDomainRestrictionsDefaultPolicy::Allow)
    {
        $this->allow = $allow;
        $this->deny = $deny;
        $this->defaultPolicy = $defaultPolicy;
    }
}
