<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Utils\SdkMetadata;
class UpdateLiveStreamUserAgentRestrictionsRequest
{
    /**
     *
     * @var string $streamId
     */
    #[SdkMetadata('pathParam:style=simple,explode=false,name=streamId')]
    public string $streamId;

    /**
     *
     * @var string $playbackId
     */
    #[SdkMetadata('pathParam:style=simple,explode=false,name=playbackId')]
    public string $playbackId;

    /**
     *
     * @var UpdateLiveStreamUserAgentRestrictionsRequestBody $body
     */
    #[SdkMetadata('request:mediaType=application/json')]
    public UpdateLiveStreamUserAgentRestrictionsRequestBody $body;

    /**
     * @param  string  $streamId
     * @param  string  $playbackId
     * @param  UpdateLiveStreamUserAgentRestrictionsRequestBody  $body
     * @phpstan-pure
     */
    public function __construct(string $streamId, string $playbackId, UpdateLiveStreamUserAgentRestrictionsRequestBody $body)
    {
        $this->streamId = $streamId;
        $this->playbackId = $playbackId;
        $this->body = $body;
    }
}
