<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;


class UpdateMediaChaptersRequestBody
{
    /**
     * Enable or disable the chapters feature for the media. Set to `true` to enable chapters or `false` to disable.
     *
     *
     *
     * @var bool $chapters
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('chapters')]
    public bool $chapters = true;

    /**
     * @param  bool  $chapters
     * @phpstan-pure
     */
    public function __construct(bool $chapters = true)
    {
        $this->chapters = $chapters;
    }
}
