<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;


/** Specify the fallback behavior for domains that are not listed in the `allow` or `deny` lists. */
enum UpdateDomainRestrictionsDefaultPolicy: string
{
    case Allow = 'allow';
    case Deny = 'deny';
}
