<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Utils\SdkMetadata;
class UpdateMediaSummaryRequest
{
    /**
     * The unique identifier assigned to the media when created. The value must be a valid UUID.
     *
     *
     *
     * @var string $mediaId
     */
    #[SdkMetadata('pathParam:style=simple,explode=false,name=mediaId')]
    public string $mediaId;

    /**
     *
     * @var UpdateMediaSummaryRequestBody $body
     */
    #[SdkMetadata('request:mediaType=application/json')]
    public UpdateMediaSummaryRequestBody $body;

    /**
     * @param  string  $mediaId
     * @param  UpdateMediaSummaryRequestBody  $body
     * @phpstan-pure
     */
    public function __construct(string $mediaId, UpdateMediaSummaryRequestBody $body)
    {
        $this->mediaId = $mediaId;
        $this->body = $body;
    }
}