<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Operations;

use FastPix\Sdk\Models\Components;
/** UpdatedSourceAccessResponseBody - Media details updated successfully */
class UpdatedSourceAccessResponseBody
{
    /**
     * Shows the request status. Returns true for success and false for failure.
     *
     * @var ?bool $success
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('success')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $success = null;

    /**
     *
     * @var ?Components\SourceAccessMedia $data
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('data')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\SourceAccessMedia|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?Components\SourceAccessMedia $data = null;

    /**
     * @param  ?bool  $success
     * @param  ?Components\SourceAccessMedia  $data
     * @phpstan-pure
     */
    public function __construct(?bool $success = null, ?Components\SourceAccessMedia $data = null)
    {
        $this->success = $success;
        $this->data = $data;
    }
}