<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Utils;

use Psr\Http\Message\StreamInterface;

/**
 * Null-object implementation of {@see StreamInterface}.
 *
 * Several predicate accessors intentionally share the same trivial body (returning
 * false) because this is a no-op placeholder. Collapsing them into a shared method
 * would leave the bodies identical and provide no real value, so the "identical
 * implementations" rule is suppressed.
 *
 * @SuppressWarnings("php:S4144")
 */
class DefaultStream implements StreamInterface
{
    public function __toString(): string
    {
        return '';
    }

    public function close(): void
    {
        // Intentionally empty: this placeholder stream holds no resource to close.
    }

    public function detach()
    {
        return null;
    }

    public function getSize(): ?int
    {
        return null;
    }

    public function tell(): int
    {
        return 0;
    }

    public function eof(): bool
    
    {
        return true;
    }

    public function isSeekable(): bool
    {
        return false;
    }

    public function seek($offset, $whence = SEEK_SET): void
    {
        // Intentionally empty: this placeholder stream is not seekable.
    }

    public function rewind(): void
    {
        // Intentionally empty: this placeholder stream is not seekable.
    }

    public function isWritable(): bool
    {
        return false;
    }

    public function write(string $string): int
    {
        return 0;
    }

    public function isReadable(): bool
    {
        return false;
    }

    public function read(int $length): string
    {
        return '';
    }

    public function getContents(): string
    {
        return '';
    }

    public function getMetadata($key = null)
    {
        return null;
    }
}
