<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Utils;

use Psr\Http\Message\UriInterface;

class DefaultUri implements UriInterface
{

    public function getScheme(): string // NOSONAR php:S4144 - PSR-7 null-object: each getter must exist and return the same empty value.
    {
        return '';
    }

    public function getAuthority(): string // NOSONAR php:S4144 - PSR-7 null-object: each getter must exist and return the same empty value.
    {
        return '';
    }

    public function getUserInfo(): string // NOSONAR php:S4144 - PSR-7 null-object: each getter must exist and return the same empty value.
    {
        return '';
    }

    public function getHost(): string // NOSONAR php:S4144 - PSR-7 null-object: each getter must exist and return the same empty value.
    {
        return '';
    }

    public function getPort(): ?int
    {
        return null;
    }

    public function getPath(): string // NOSONAR php:S4144 - PSR-7 null-object: each getter must exist and return the same empty value.
    {
        return '';
    }

    public function getQuery(): string // NOSONAR php:S4144 - PSR-7 null-object: each getter must exist and return the same empty value.
    {
        return '';
    }

    public function getFragment(): string // NOSONAR php:S4144 - PSR-7 null-object: each getter must exist and return the same empty value.
    {
        return '';
    }

    public function withScheme($scheme): UriInterface
    {
        return $this;
    }

    public function withUserInfo($user, $password = null): UriInterface
    {
        return $this;
    }

    public function withHost(string $host): UriInterface
    {
        return $this;
    }

    public function withPort($port): UriInterface
    {
        return $this;
    }

    public function withPath($path): UriInterface
    {
        return $this;
    }

    public function withQuery($query): UriInterface
    {
        return $this;
    }

    public function withFragment($query): UriInterface
    {
        return $this;
    }

    public function __toString(): string
    {
        return '';
    }
}
