<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Utils;


use FastPix\Sdk\Serializer\Handler\ArrayCollectionHandler;
use FastPix\Sdk\Serializer\Handler\HandlerRegistry;
use FastPix\Sdk\Serializer\Handler\IteratorHandler;
use FastPix\Sdk\Serializer\Handler\StdClassHandler;
use FastPix\Sdk\Serializer\SerializationContext;
use FastPix\Sdk\Serializer\SerializerBuilder;


class JSON
{
    public static function createSerializer(): \FastPix\Sdk\Serializer\Serializer
    {
        return SerializerBuilder::create()->configureHandlers(
            static function (HandlerRegistry $registry): void {
                $registry->registerSubscribingHandler(new StdClassHandler());
                $registry->registerSubscribingHandler(new ArrayCollectionHandler());
                $registry->registerSubscribingHandler(new IteratorHandler());
                $registry->registerSubscribingHandler(new MixedJSONHandler());
                $registry->registerSubscribingHandler(new EnumHandler());
                $registry->registerSubscribingHandler(new DateTimeHandler());
                $registry->registerSubscribingHandler(new DateHandler());
                $registry->registerSubscribingHandler(new UnionHandler());
                $registry->registerSubscribingHandler(new BigIntHandler());
                $registry->registerSubscribingHandler(new BigDecimalHandler());
            },
        )->setTypeParser(new PhpDocTypeParser()
        )->setSerializationContextFactory(function () {
            return SerializationContext::create()
                ->setSerializeNull(true);
        })->build();
    }
}
