<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Utils;

use ReflectionProperty;

class PathParameters
{
    /**
     * @param  class-string  $type
     * @param  mixed  $pathParams
     * @param  array<string,array<string,array<string,string>>>|null  $globals
     * @return array<string,string>
     */
    public function parsePathParams(string $type, mixed $pathParams, ?array $globals): array
    {
        $parsed = [];

        $fields = array_keys(get_class_vars($type));

        foreach ($fields as $field) {
            $value = $pathParams !== null ? $pathParams->{$field} : null;

            if ($globals !== null) {
                $value = populateGlobal($value, 'pathParam', $field, $globals);
            }

            if ($value === null) {
                continue;
            }

            $requestMetadata = RequestBodies::parseRequestMetadata(new ReflectionProperty($type, $field));
            if ($requestMetadata !== null) {
                continue;
            }

            $metadata = $this->parsePathParamsMetadata(new ReflectionProperty($type, $field));
            if ($metadata === null) {
                continue;
            }

            if (! empty($metadata->serialization)) {
                $parsed = array_merge_recursive($parsed, $this->parseSerializationParams($metadata, $value));
            } else {
                match ($metadata->style) {
                    'simple' => $parsed = array_merge_recursive($parsed, $this->parseSimplePathParams($metadata, $value)),
                    default => throw new \InvalidArgumentException('Unsupported style: '.$metadata->style),
                };
            }
        }

        return $parsed;
    }

    /**
     * @param  ParamsMetadata  $metadata
     * @param  mixed  $value
     * @return array<string,string>
     */
    private function parseSimplePathParams(ParamsMetadata $metadata, mixed $value): array
    {
        $pathParams = [];

        switch (gettype($value)) {
            case 'object':
                $pathParams[$metadata->name] = $this->serializeObjectPathParam($metadata, $value);
                break;
            case 'array':
                $pathParams[$metadata->name] = $this->serializeArrayPathParam($metadata, $value);
                break;
            default:
                $pathParams[$metadata->name] = valToString($value, []);
                break;
        }

        return $pathParams;
    }

    /**
     * @param  ParamsMetadata  $metadata
     * @param  object  $value
     * @return string
     */
    private function serializeObjectPathParam(ParamsMetadata $metadata, object $value): string
    {
        if ($value instanceof \Brick\Math\BigDecimal || $value instanceof \Brick\Math\BigInteger || $value instanceof \Brick\DateTime\LocalDate || $value instanceof \DateTime || $value instanceof \UnitEnum) {
            return valToString($value, $metadata->encodingArray());
        }

        $vals = [];
        foreach ($value as $field => $fieldValue) { /** @phpstan-ignore-line */
            if ($fieldValue === null) {
                continue;
            }

            $fieldMetadata = $this->parsePathParamsMetadata(new ReflectionProperty($value::class, $field));
            if ($fieldMetadata === null) {
                continue;
            }

            $format = $metadata->explode ? '%s=%s' : '%s,%s';
            $vals[] = sprintf($format, $fieldMetadata->name, valToString($fieldValue, $fieldMetadata->encodingArray()));
        }

        return implode(',', $vals);
    }

    /**
     * @param  ParamsMetadata  $metadata
     * @param  array<mixed>  $value
     * @return string
     */
    private function serializeArrayPathParam(ParamsMetadata $metadata, array $value): string
    {
        $vals = [];

        if (array_is_list($value)) {
            foreach ($value as $val) {
                $vals[] = valToString($val, []);
            }
        } else {
            foreach ($value as $key => $val) {
                $format = $metadata->explode ? '%s=%s' : '%s,%s';
                $vals[] = sprintf($format, $key, valToString($val, []));
            }
        }

        return implode(',', $vals);
    }

    private function parsePathParamsMetadata(ReflectionProperty $property): ?ParamsMetadata
    {
        $metadataStr = SdkMetadata::find($property->getAttributes(SdkMetadata::class), 'pathParam');
        if ($metadataStr === null) {
            return null;
        }

        $metadata = ParamsMetadata::parse($metadataStr);
        if ($metadata === null) {
            return null;
        }

        return $metadata;
    }

    /**
     * @param  ParamsMetadata  $metadata
     * @param  mixed  $value
     * @return array<string,string>
     */
    private function parseSerializationParams(ParamsMetadata $metadata, mixed $value): array
    {
        $params = [];

        $params[$metadata->name] = match ($metadata->serialization) {
            'json' => urlencode(JSON::createSerializer()->serialize($value, 'json')),
            default => throw new \InvalidArgumentException('Unsupported serialization: '.$metadata->serialization),
        };

        return $params;
    }
}
