<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Utils;

class RequestMetadata
{
    private function __construct(
        public string $mediaType,
    ) {
    }

    public static function parse(string $metadata): ?RequestMetadata
    {
        if (! str_starts_with($metadata, 'request:')) {
            return null;
        }

        $metadata = removePrefix($metadata, 'request:');

        $mediaType = '';

        $options = explode(',', $metadata);

        foreach ($options as $opt) {
            $parts = explode('=', $opt);
            if (empty($parts) || count($parts) > 2) { /** @phpstan-ignore-line */
                continue;
            }

            match ($parts[0]) {
                'mediaType' => $mediaType = $parts[1],
                default => throw new \InvalidArgumentException(sprintf('Invalid request metadata option "%s".', $parts[0])),
            };
        }

        return new RequestMetadata(
            mediaType: $mediaType,
        );
    }
}
