<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** AddTrackRequest - Contains details about the track being added to the media file. */
class AddTrackRequest
{
    /**
     * The direct URL of the track file. It must point to a valid audio or subtitle file.
     *
     * @var ?string $url
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('url')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $url = null;

    /**
     * Specifies the type of track being added. It can be either `audio` or `subtitle`.
     *
     * @var ?AddTrackRequestType $type
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('type')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\AddTrackRequestType|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?AddTrackRequestType $type = null;

    /**
     * The BCP 47 language code representing the track’s language.
     *
     * @var ?string $languageCode
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('languageCode')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $languageCode = null;

    /**
     * The full name of the language corresponding to the `languageCode`.
     *
     * @var ?string $languageName
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('languageName')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $languageName = null;

    /**
     * @param  ?string  $url
     * @param  ?AddTrackRequestType  $type
     * @param  ?string  $languageCode
     * @param  ?string  $languageName
     * @phpstan-pure
     */
    public function __construct(?string $url = 'https://static.fastpix.com/music-1.mp3', ?AddTrackRequestType $type = AddTrackRequestType::Audio, ?string $languageCode = 'it', ?string $languageName = 'Italian')
    {
        $this->url = $url;
        $this->type = $type;
        $this->languageCode = $languageCode;
        $this->languageName = $languageName;
    }
}
