<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


class CreateMediaResponse
{
    /**
     * The Media is assigned a universal unique identifier, which can contain a maximum of 255 characters.
     *
     * @var ?string $id
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('id')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Determines the media's status, which can be one of the possible values.
     *
     * @var ?CreateMediaResponseStatus $status
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('status')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\CreateMediaResponseStatus|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?CreateMediaResponseStatus $status = null;

    /**
     * Time the media was created, defined as a localDateTime (UTC Time).
     *
     * @var ?\DateTime $createdAt
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('createdAt')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * Time the media was updated, defined as a localDateTime (UTC Time).
     *
     * @var ?\DateTime $updatedAt
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('updatedAt')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     * A collection of Playback ID objects utilized for crafting HLS playback URLs.
     *
     * @var ?array<PlaybackId> $playbackIds
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('playbackIds')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('array<\FastPix\Sdk\Models\Components\PlaybackId>|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?array $playbackIds = null;

    /**
     * You can search for videos with specific key value pairs using metadata, when you tag a video in "key" : "value" pairs. Dynamic metadata allows you to define a key that allows any value pair. You can have maximum of 255 characters and upto 10 entries are allowed.
     *
     *
     *
     * @var ?array<string, string> $metadata
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('metadata')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('array<string, string>|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * The quality tier applied to the media.
     *
     * @var ?CreateMediaResponseMediaQuality $mediaQuality
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('mediaQuality')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\CreateMediaResponseMediaQuality|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?CreateMediaResponseMediaQuality $mediaQuality = null;

    /**
     * The sourceAccess parameter determines whether the original media file is accessible. Set to true to enable access or false to restrict it.
     *
     *
     *
     * @var ?bool $sourceAccess
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('sourceAccess')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $sourceAccess = null;

    /**
     * The maximum resolution tier defines the highest quality at which your media is available.
     *
     * @var ?CreateMediaResponseMaxResolution $maxResolution
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('maxResolution')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\CreateMediaResponseMaxResolution|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?CreateMediaResponseMaxResolution $maxResolution = null;

    /**
     * A list of media input sources to be processed.
     *
     * @var ?array<CreateMediaResponseInput> $inputs
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('inputs')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('array<\FastPix\Sdk\Models\Components\CreateMediaResponseInput>|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?array $inputs = null;

    /**
     * Enhance the quality and volume of the audio track. This is available for pre-recorded content only.
     *
     *
     *
     * @var ?bool $optimizeAudio
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('optimizeAudio')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $optimizeAudio = null;

    /**
     * FastPix allows for a free trial. Create as many media files as you like during the trial period. Remember, each clip can only be 10 seconds long and will be deleted after 24 hours. Also, all trial content will have the FastPix logo watermark.
     *
     *
     *
     * @var ?bool $trial
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('trial')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $trial = true;
}
