<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


class CreateMediaResponseInput
{
    /**
     * The type of input media. Commonly set to `video`.
     *
     * @var ?string $type
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('type')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $type = null;

    /**
     * The publicly accessible URL of the input video file.
     *
     * @var ?string $url
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('url')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $url = null;

    /**
     * @param  ?string  $type
     * @param  ?string  $url
     * @phpstan-pure
     */
    public function __construct(?string $type = null, ?string $url = null)
    {
        $this->type = $type;
        $this->url = $url;
    }
}
