<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** CreateSigningKeyResponseDTO - Displays the result of the request. */
class CreateSigningKeyResponseDTO
{
    /**
     * A unique identifier is generated by FastPix for the signing keys.
     *
     * @var ?string $id
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('id')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * A private key is a byte encoded secret key used to create a signed JSON Web Token (JWT) for authentication.
     *
     * @var ?string $privateKey
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('privateKey')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $privateKey = null;

    /**
     * Time the Signing key was generated, defined as a localDateTime (UTC Time).
     *
     * @var ?\DateTime $createdAt
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('createdAt')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $privateKey
     * @param  ?\DateTime  $createdAt
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?string $privateKey = null, ?\DateTime $createdAt = null)
    {
        $this->id = $id;
        $this->privateKey = $privateKey;
        $this->createdAt = $createdAt;
    }
}
