<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


class CreateMediaRequestDomains
{
    /**
     * Specifies the default access policy for domains.
     *
     * If set to `allow`, all domains are allowed access unless otherwise specified in the `deny` lists.
     * If set to `deny`, all domains are denied access unless otherwise specified in the `allow` lists.
     *
     *
     * @var ?DomainsDefaultPolicy $defaultPolicy
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('defaultPolicy')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\DomainsDefaultPolicy|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?DomainsDefaultPolicy $defaultPolicy = null;

    /**
     * A list of domain names or patterns that are explicitly allowed access.
     *
     * This list is only effective when the `defaultPolicy` is set to `deny`.
     *
     *
     * @var ?array<string> $allow
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('allow')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('array<string>|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?array $allow = null;

    /**
     * A list of domain names or patterns that are explicitly denied access.
     *
     * This list is only effective when the `defaultPolicy` is set to `allow`.
     *
     *
     * @var ?array<string> $deny
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('deny')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('array<string>|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?array $deny = null;

    /**
     * @param  ?DomainsDefaultPolicy  $defaultPolicy
     * @param  ?array<string>  $allow
     * @param  ?array<string>  $deny
     * @phpstan-pure
     */
    public function __construct(?DomainsDefaultPolicy $defaultPolicy = null, ?array $allow = null, ?array $deny = null)
    {
        $this->defaultPolicy = $defaultPolicy;
        $this->allow = $allow;
        $this->deny = $deny;
    }
}
