<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/**
 * Defines the type of input. Possible values include video, audio, av.
 *
 *
 */
enum CreateMediaRequestType: string
{
    case Video = 'video';
    case Audio = 'audio';
    case Av = 'av';
}
