<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/**
 * Defines the maximum resolution for encoding, storage, and playback of the live stream.
 *
 *
 */
enum CreateLiveStreamRequestMaxResolution: string
{
    case OneThousandAndEightyp = '1080p';
    case SevenHundredAndTwentyp = '720p';
    case FourHundredAndEightyp = '480p';
}
