<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/**
 * Specifies the default access policy for domains. 
 *
 * If set to `allow`, all domains are allowed access unless otherwise specified in the `deny` lists. 
 * If set to `deny`, all domains are denied access unless otherwise specified in the `allow` lists.
 *
 */
enum CreateMediaRequestDomainsDefaultPolicy: string
{
    case Allow = 'allow';
    case Deny = 'deny';
}
