<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


class CreateMediaRequestAccessRestrictions
{
    /**
     *
     * @var ?CreateMediaRequestDomains $domains
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('domains')]
    #[\Speakeasy\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\CreateMediaRequestDomains|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateMediaRequestDomains $domains = null;

    /**
     *
     * @var ?CreateMediaRequestUserAgents $userAgents
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('userAgents')]
    #[\Speakeasy\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\CreateMediaRequestUserAgents|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CreateMediaRequestUserAgents $userAgents = null;

    /**
     * @param  ?CreateMediaRequestDomains  $domains
     * @param  ?CreateMediaRequestUserAgents  $userAgents
     * @phpstan-pure
     */
    public function __construct(?CreateMediaRequestDomains $domains = null, ?CreateMediaRequestUserAgents $userAgents = null)
    {
        $this->domains = $domains;
        $this->userAgents = $userAgents;
    }
}