<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/**
 * Specifies the default access policy for user agents (browsers, bots, etc.).
 *
 * If set to `allow`, all user agents are allowed access unless otherwise specified in the `deny` lists. 
 * If set to `deny`, all user agents are denied access unless otherwise specified in the `allow` lists.
 *
 */
enum CreateMediaRequestUserAgentsDefaultPolicy: string
{
    case Allow = 'allow';
    case Deny = 'deny';
}
