<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


class CreatePlaylistRequestManual
{
    /**
     * Name of the playlist.
     *
     * @var string $name
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Unique string value assigned by user to the playlist.
     *
     * @var string $referenceId
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('referenceId')]
    public string $referenceId;

    /**
     * Manual playlist type (no `playOrder`).
     *
     * @var CreatePlaylistRequestManualType $type
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('type')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\CreatePlaylistRequestManualType')]
    public CreatePlaylistRequestManualType $type;

    /**
     * Description for a playlist (Optional).
     *
     * @var ?string $description
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('description')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * Optional parameter to limit no. of media in a playlist.
     *
     * @var ?int $limit
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('limit')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?int $limit = null;

    /**
     * @param  string  $name
     * @param  string  $referenceId
     * @param  CreatePlaylistRequestManualType  $type
     * @param  ?string  $description
     * @param  ?int  $limit
     * @phpstan-pure
     */
    public function __construct(string $name, string $referenceId, CreatePlaylistRequestManualType $type, ?string $description = null, ?int $limit = 1000)
    {
        $this->name = $name;
        $this->referenceId = $referenceId;
        $this->type = $type;
        $this->description = $description;
        $this->limit = $limit;
    }
}
