<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


class CreateLiveStreamRequest
{
    /**
     * Displays the result of the playback settings.
     *
     * @var PlaybackSettings $playbackSettings
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('playbackSettings')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\PlaybackSettings')]
    public PlaybackSettings $playbackSettings;

    /**
     * Contains configuration details for input media settings.
     *
     * @var InputMediaSettings $inputMediaSettings
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('inputMediaSettings')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\InputMediaSettings')]
    public InputMediaSettings $inputMediaSettings;

    /**
     * @param  PlaybackSettings  $playbackSettings
     * @param  InputMediaSettings  $inputMediaSettings
     * @phpstan-pure
     */
    public function __construct(PlaybackSettings $playbackSettings, InputMediaSettings $inputMediaSettings)
    {
        $this->playbackSettings = $playbackSettings;
        $this->inputMediaSettings = $inputMediaSettings;
    }
}
