<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


class DefaultError
{
    /**
     * Shows if the request was completed successfully. Returns `true` for success and `false` for failure.
     *
     * @var ?bool $success
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('success')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $success = null;

    /**
     * Contains details about the error if the request failed.
     *
     * @var ?Error $error
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('error')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\Error|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?Error $error = null;

    /**
     * @param  ?bool  $success
     * @param  ?Error  $error
     * @phpstan-pure
     */
    public function __construct(?bool $success = null, ?Error $error = null)
    {
        $this->success = $success;
        $this->error = $error;
    }
}