<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** DirectUpload - Displays the result of the request. */
class DirectUpload
{
    /**
     * The unique identifier assigned to the media when created. The value must be a valid UUID.
     *
     * @var ?string $uploadId
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('uploadId')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $uploadId = null;

    /**
     * Indicates if the upload was a trial.
     *
     * @var ?bool $trial
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('trial')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $trial = null;

    /**
     * Determines the media's status, which can be one of the possible values.
     *
     * @var ?DirectUploadStatus $status
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('status')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\DirectUploadStatus|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?DirectUploadStatus $status = null;

    /**
     * The url hosts the media file for FastPix, which needs to be download to use further.  It supports formats like MP3, MP4, MOV, MKV, or TS, and includes text tracks for subtitles/CC (SRT file/VTT file). While FastPix can handle various audio and video formats and codecs, using standard inputs can help with optimal processing speed.
     *
     * @var ?string $url
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('url')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $url = null;

    /**
     * Upload media directly from a device using the url name or enter "*" to allow all.
     *
     * @var ?string $corsOrigin
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('corsOrigin')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $corsOrigin = null;

    /**
     *
     * @var ?DirectUploadResponse $pushMediaSettings
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('pushMediaSettings')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\DirectUploadResponse|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?DirectUploadResponse $pushMediaSettings = null;

    /**
     * The duration set for the validity of the upload URL. If the upload isn't completed within this timespan, it's marked as timed out.
     *
     *
     *
     * @var ?float $timeout
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('timeout')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?float $timeout = null;

    /**
     * @param  ?string  $uploadId
     * @param  ?bool  $trial
     * @param  ?DirectUploadStatus  $status
     * @param  ?string  $url
     * @param  ?float  $timeout
     * @param  ?string  $corsOrigin
     * @param  ?DirectUploadResponse  $pushMediaSettings
     * @phpstan-pure
     */
    public function __construct(?string $uploadId = null, ?bool $trial = null, ?DirectUploadStatus $status = null, ?string $url = null, ?string $corsOrigin = null, ?DirectUploadResponse $pushMediaSettings = null, ?float $timeout = 14400)
    {
        $this->uploadId = $uploadId;
        $this->trial = $trial;
        $this->status = $status;
        $this->url = $url;
        $this->corsOrigin = $corsOrigin;
        $this->pushMediaSettings = $pushMediaSettings;
        $this->timeout = $timeout;
    }
}
