<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


class ErrorDetails
{
    /**
     * views affected by the specific errors.
     *
     * @var int|float|null $percentage
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('percentage')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('int|float|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public int|float|null $percentage = null;

    /**
     * Information about the specific error.
     *
     * @var ?string $notes
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('notes')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $notes = null;

    /**
     * error message or description.
     *
     * @var ?string $message
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('message')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $message = null;

    /**
     * The timestamp of when the error was last observed.
     *
     * @var ?string $lastSeen
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('lastSeen')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $lastSeen = null;

    /**
     * Unique identifier for the error instance.
     *
     * @var ?string $id
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('id')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * A brief description of the error.
     *
     * @var ?string $description
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('description')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * Number of occurrences of the specific error.
     *
     * @var ?int $count
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('count')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?int $count = null;

    /**
     * Error code associated with the specific error.
     *
     * @var ?string $code
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('code')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $code = null;
}
