<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** GenerateTrackResponse - Represents the response for a successfully generated subtitle track. */
class GenerateTrackResponse
{
    /**
     * A unique identifier for the generated track.
     *
     * @var ?string $id
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('id')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * The type of track generated ("subtitle").
     *
     * @var ?GenerateTrackResponseType $type
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('type')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\GenerateTrackResponseType|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?GenerateTrackResponseType $type = null;

    /**
     * The BCP 47 language code representing the language of the generated track.
     *
     *
     *
     * @var ?GenerateTrackResponseLanguageCode $languageCode
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('languageCode')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\GenerateTrackResponseLanguageCode|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?GenerateTrackResponseLanguageCode $languageCode = null;

    /**
     * The full name of the language for the generated track.
     *
     * @var ?string $languageName
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('languageName')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $languageName = null;

    /**
     * You can search for videos with specific key value pairs using metadata, when you tag a video in "key" : "value" pairs. Dynamic metadata allows you to define a key that allows any value pair. You can have maximum of 255 characters and upto 10 entries are allowed.
     *
     *
     *
     * @var ?array<string, string> $metadata
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('metadata')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('array<string, string>|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * Title of the track.
     *
     * @var ?string $title
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('title')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     * @param  ?string  $id
     * @param  ?GenerateTrackResponseType  $type
     * @param  ?GenerateTrackResponseLanguageCode  $languageCode
     * @param  ?string  $languageName
     * @param  ?array<string, string>  $metadata
     * @param  ?string  $title
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?GenerateTrackResponseType $type = null, ?GenerateTrackResponseLanguageCode $languageCode = null, ?string $languageName = null, ?array $metadata = null, ?string $title = null)
    {
        $this->id = $id;
        $this->type = $type;
        $this->languageCode = $languageCode;
        $this->languageName = $languageName;
        $this->metadata = $metadata;
        $this->title = $title;
    }
}
