<?php



declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


class GetAllSigningKeyResponseDTO
{
    /**
     * A unique identifier is generated by FastPix for the signing keys.
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Time the media was generated, defined as a localDateTime (UTC Time).
     *
     * @var ?\DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * It display a specific setup where all operations are conducted.
     *
     * @var ?array<SigningKeyWorkspaceDTO> $workspace
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('workspace')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\FastPix\Sdk\Models\Components\SigningKeyWorkspaceDTO>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $workspace = null;

    /**
     * Pagination organizes content into pages for better readability and navigation.
     *
     * @var ?SingingKeysPagination $pagination
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pagination')]
    #[\Speakeasy\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\SingingKeysPagination|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SingingKeysPagination $pagination = null;

    /**
     * @param  ?string  $id
     * @param  ?\DateTime  $createdAt
     * @param  ?array<SigningKeyWorkspaceDTO>  $workspace
     * @param  ?SingingKeysPagination  $pagination
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?\DateTime $createdAt = null, ?array $workspace = null, ?SingingKeysPagination $pagination = null)
    {
        $this->id = $id;
        $this->createdAt = $createdAt;
        $this->workspace = $workspace;
        $this->pagination = $pagination;
    }
}