<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


class GetAllPlaylistsResponse
{
    /**
     * Shows the request status. Returns true for success and false for failure.
     *
     * @var bool $success
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('success')]
    public bool $success;

    /**
     * $data
     *
     * @var array<PlaylistItem> $data
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('data')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('array<\FastPix\Sdk\Models\Components\PlaylistItem>')]
    public array $data;

    /**
     * Pagination organizes content into pages for better readability and navigation.
     *
     * @var ?Pagination $pagination
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('pagination')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\Pagination|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?Pagination $pagination = null;

    /**
     * @param  bool  $success
     * @param  array<PlaylistItem>  $data
     * @param  ?Pagination  $pagination
     * @phpstan-pure
     */
    public function __construct(bool $success, array $data, ?Pagination $pagination = null)
    {
        $this->success = $success;
        $this->data = $data;
        $this->pagination = $pagination;
    }
}