<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** GetPublicPemUsingSigningKeyIdResponseDTOData - Displays the result of the request. */
class GetPublicPemUsingSigningKeyIdResponseDTOData
{
    /**
     * FastPix generates a unique identifier for each workspace.
     *
     * @var ?string $workspaceId
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('workspaceId')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $workspaceId = null;

    /**
     *
     * @var ?string $signingKeyId
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('signingKeyId')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $signingKeyId = null;

    /**
     * A public key is a byte encoded key used to create a signed JSON Web Token (JWT) for authentication.
     *
     * @var ?string $publicKey
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('publicKey')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $publicKey = null;

    /**
     * @param  ?string  $workspaceId
     * @param  ?string  $signingKeyId
     * @param  ?string  $publicKey
     * @phpstan-pure
     */
    public function __construct(?string $workspaceId = null, ?string $signingKeyId = null, ?string $publicKey = null)
    {
        $this->workspaceId = $workspaceId;
        $this->signingKeyId = $signingKeyId;
        $this->publicKey = $publicKey;
    }
}
