<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** GetStreamsResponse - Displays the result of the request. */
class GetStreamsResponse
{
    /**
     * Shows the request status. Returns true for success and false for failure.
     *
     * @var ?bool $success
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('success')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $success = null;

    /**
     * Displays the result of the request.
     *
     * @var ?array<GetCreateLiveStreamResponseDTO> $data
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('data')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('array<\FastPix\Sdk\Models\Components\GetCreateLiveStreamResponseDTO>|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?array $data = null;

    /**
     * Pagination organizes content into pages for better readability and navigation.
     *
     * @var ?LiveStreamPagination $pagination
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('pagination')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\LiveStreamPagination|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?LiveStreamPagination $pagination = null;

    /**
     * @param  ?bool  $success
     * @param  ?array<GetCreateLiveStreamResponseDTO>  $data
     * @param  ?LiveStreamPagination  $pagination
     * @phpstan-pure
     */
    public function __construct(?bool $success = null, ?array $data = null, ?LiveStreamPagination $pagination = null)
    {
        $this->success = $success;
        $this->data = $data;
        $this->pagination = $pagination;
    }
}
