<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** InputMediaSettings - Contains configuration details for input media settings. */
class InputMediaSettings
{
    /**
     * Custom key–value pairs for tagging livestreams.
     *
     * Allows up to 10 entries with a maximum of 255 characters each.
     *
     *
     * @var ?array<string, string> $metadata
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('metadata')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('array<string, string>|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * Enables DVR (Digital Video Recorder) functionality, allowing viewers to pause, rewind, and resume live playback.
     *
     *
     *
     * @var ?bool $enableDvrMode
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('enableDvrMode')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $enableDvrMode = null;

    /**
     * Defines the maximum resolution for encoding, storage, and playback of the live stream.
     *
     *
     *
     * @var ?CreateLiveStreamRequestMaxResolution $maxResolution
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('maxResolution')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\CreateLiveStreamRequestMaxResolution|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?CreateLiveStreamRequestMaxResolution $maxResolution = null;

    /**
     * Time period (in seconds) FastPix waits to reconnect before ending the stream when disconnected.
     *
     *
     *
     * @var ?int $reconnectWindow
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('reconnectWindow')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?int $reconnectWindow = null;

    /**
     * Basic access policy for media content
     *
     * @var ?BasicAccessPolicy $mediaPolicy
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('mediaPolicy')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\BasicAccessPolicy|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?BasicAccessPolicy $mediaPolicy = null;

    /**
     * @param  ?CreateLiveStreamRequestMaxResolution  $maxResolution
     * @param  ?int  $reconnectWindow
     * @param  ?BasicAccessPolicy  $mediaPolicy
     * @param  ?array<string, string>  $metadata
     * @param  ?bool  $enableDvrMode
     * @phpstan-pure
     */
    public function __construct(?array $metadata = null, ?bool $enableDvrMode = null, ?CreateLiveStreamRequestMaxResolution $maxResolution = CreateLiveStreamRequestMaxResolution::OneThousandAndEightyp, ?int $reconnectWindow = 60, ?BasicAccessPolicy $mediaPolicy = BasicAccessPolicy::Public)
    {
        $this->metadata = $metadata;
        $this->enableDvrMode = $enableDvrMode;
        $this->maxResolution = $maxResolution;
        $this->reconnectWindow = $reconnectWindow;
        $this->mediaPolicy = $mediaPolicy;
    }
}
