<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** Determines the media's status, which can be one of the possible values. */
enum LiveMediaClipsStatus: string
{
    case Created = 'Created';
    case Downloading = 'Downloading';
    case Downloaded = 'Downloaded';
    case Validating = 'Validating';
    case InQueue = 'In Queue';
    case Processing = 'Processing';
    case Ready = 'Ready';
    case Failed = 'Failed';
}
