<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** The maximum resolution specified by the user for the media. */
enum MediaMaxResolution: string
{
    case TwoThousandOneHundredAndSixtyp = '2160p';
    case OneThousandFourHundredAndFortyp = '1440p';
    case OneThousandAndEightyp = '1080p';
    case SevenHundredAndTwentyp = '720p';
    case FourHundredAndEightyp = '480p';
}
