<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** MediaCancelResponse - Response returned when an upload is cancelled. */
class MediaCancelResponse
{
    /**
     * The unique identifier of the cancelled upload.
     *
     * @var ?string $uploadId
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('uploadId')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $uploadId = null;

    /**
     * Indicates if the upload was a trial.
     *
     * @var ?bool $trial
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('trial')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $trial = null;

    /**
     * The status of the upload after cancellation.
     *
     * @var ?string $status
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('status')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $status = null;

    /**
     * The upload URL (if available) after cancellation.
     *
     * @var ?string $url
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('url')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $url = null;

    /**
     * CORS origin allowed for the upload.
     *
     * @var ?string $corsOrigin
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('corsOrigin')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $corsOrigin = null;

    /**
     * The maximum resolution allowed for the upload.
     *
     * @var ?string $maxResolution
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('maxResolution')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $maxResolution = null;

    /**
     * The access policy for the upload.
     *
     * @var ?string $accessPolicy
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('accessPolicy')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $accessPolicy = null;

    /**
     * You can search for videos with specific key value pairs using metadata, when you tag a video in "key" : "value" pairs. Dynamic metadata allows you to define a key that allows any value pair. You can have maximum of 255 characters and upto 10 entries are allowed.
     *
     *
     *
     * @var ?array<string, string> $metadata
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('metadata')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('array<string, string>|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * The timeout value for the upload.
     *
     * @var ?int $timeout
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('timeout')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?int $timeout = null;

    /**
     * Title of the media file.
     *
     * @var ?string $title
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('title')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     * The unique identifier of the user who created this media.
     *
     * @var ?string $creatorId
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('creatorId')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $creatorId = null;
}
