<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/**
 * MediaMp4Support - Details of an MP4 rendition generated for the media.
 *
 * Each entry describes a single MP4 rendition, for example a `capped_4k` video
 * rendition or an `audioOnly` rendition. Audio-only renditions have no height or width.
 *
 */
class MediaMp4Support
{
    /**
     * The type of MP4 rendition, for example `capped_4k` or `audioOnly`.
     *
     * @var ?string $type
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('type')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $type = null;

    /**
     * The current status of the MP4 rendition, for example `preparing` or `ready`.
     *
     * @var ?string $status
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('status')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $status = null;

    /**
     * The height of the rendition in pixels. Absent for audio-only renditions.
     *
     * @var ?int $height
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('height')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?int $height = null;

    /**
     * The width of the rendition in pixels. Absent for audio-only renditions.
     *
     * @var ?int $width
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('width')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?int $width = null;

    /**
     * The file extension of the rendition, for example `mp4` or `m4a`.
     *
     * @var ?string $ext
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('ext')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $ext = null;

    /**
     * @param  ?string  $type
     * @param  ?string  $status
     * @param  ?int  $height
     * @param  ?int  $width
     * @param  ?string  $ext
     * @phpstan-pure
     */
    public function __construct(?string $type = null, ?string $status = null, ?int $height = null, ?int $width = null, ?string $ext = null)
    {
        $this->type = $type;
        $this->status = $status;
        $this->height = $height;
        $this->width = $width;
        $this->ext = $ext;
    }
}
