<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


class MediaClipResponseData
{
    /**
     * The unique identifier assigned to the media by FastPix.
     *
     * @var ?string $id
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('id')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Duration of the media in seconds.
     *
     * @var ?float $duration
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('duration')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?float $duration = null;

    /**
     * The current processing status of the media.
     *
     * @var MediaClipResponseStatus|string|null $status
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('status')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\MediaClipResponseStatus|string|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public MediaClipResponseStatus|string|null $status = null;

    /**
     * A video thumbnail that acts as a preview image for the video.
     *
     * @var ?string $thumbnail
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('thumbnail')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $thumbnail = null;

    /**
     * Timestamp of when the media was created.
     *
     * @var ?\DateTime $createdAt
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('createdAt')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * $playbackIds
     *
     * @var ?array<MediaClipResponsePlaybackId> $playbackIds
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('playbackIds')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('array<\FastPix\Sdk\Models\Components\MediaClipResponsePlaybackId>|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?array $playbackIds = null;

    /**
     * The frame rate of the media in frames per second (for example "30/1").
     *
     * @var ?string $frameRate
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('frameRate')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $frameRate = null;

    /**
     * @param  ?string  $id
     * @param  ?float  $duration
     * @param  MediaClipResponseStatus|string|null  $status
     * @param  ?string  $thumbnail
     * @param  ?\DateTime  $createdAt
     * @param  ?array<MediaClipResponsePlaybackId>  $playbackIds
     * @param  ?string  $frameRate
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?float $duration = null, MediaClipResponseStatus|string|null $status = null, ?string $thumbnail = null, ?\DateTime $createdAt = null, ?array $playbackIds = null, ?string $frameRate = null)
    {
        $this->id = $id;
        $this->duration = $duration;
        $this->status = $status;
        $this->thumbnail = $thumbnail;
        $this->createdAt = $createdAt;
        $this->playbackIds = $playbackIds;
        $this->frameRate = $frameRate;
    }
}
