<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** MetricsComparisonDetails - Compare multiple metrics across specified dimensions. */
class MetricsComparisonDetails
{
    /**
     * The specific metric value calculated based on the applied filters.
     *
     * @var ?float $value
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('value')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?float $value = null;

    /**
     * value can be score that ranges from 0 to 100
     *
     * @var ?string $type
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('type')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $type = null;

    /**
     * value can be score that ranges from 0 to 100
     *
     * @var ?string $name
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('name')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * The metric field represents the name of the Key Performance Indicator (KPI) being tracked or analyzed. It identifies a specific measurable aspect of the video playback experience, such as buffering time, video start failure rate, or playback quality.
     *
     *
     *
     * @var ?string $metric
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('metric')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $metric = null;

    /**
     * value can be avg, sum, count or 95th
     *
     * @var ?string $measurement
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('measurement')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $measurement = null;

    /**
     * Nested comparison items
     *
     * @var ?array<MetricsComparisonDetails> $items
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('items')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('array<\FastPix\Sdk\Models\Components\MetricsComparisonDetails>|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?array $items = null;

    /**
     * @param  ?float  $value
     * @param  ?string  $type
     * @param  ?string  $name
     * @param  ?string  $metric
     * @param  ?string  $measurement
     * @param  ?array<MetricsComparisonDetails>  $items
     * @phpstan-pure
     */
    public function __construct(?float $value = null, ?string $type = null, ?string $name = null, ?string $metric = null, ?string $measurement = null, ?array $items = null)
    {
        $this->value = $value;
        $this->type = $type;
        $this->name = $name;
        $this->metric = $metric;
        $this->measurement = $measurement;
        $this->items = $items;
    }
}