<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** MetricsOverallDataDetails - Retrieves overall values for a specified metric */
class MetricsOverallDataDetails
{
    /**
     * metric value calculated based on the applied filters.
     *
     * @var ?float $value
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('value')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?float $value = null;

    /**
     * Total time watched across all views, represented in milliseconds.
     *
     * @var ?int $totalWatchTime
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('totalWatchTime')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?int $totalWatchTime = null;

    /**
     * The count of unique viewers who interacted with the content.
     *
     * @var ?int $uniqueViews
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('uniqueViews')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?int $uniqueViews = null;

    /**
     * The total number of views recorded.
     *
     * @var ?int $totalViews
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('totalViews')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?int $totalViews = null;

    /**
     * Total time spent playing the video, represented in milliseconds.
     *
     * @var ?int $totalPlayTime
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('totalPlayTime')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?int $totalPlayTime = null;

    /**
     * A global metric value that reflects the overall performance of the specified metric across the entire dataset for the given timespan.
     *
     * @var ?float $globalValue
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('globalValue')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?float $globalValue = null;

    /**
     * @param  ?float  $value
     * @param  ?int  $totalWatchTime
     * @param  ?int  $uniqueViews
     * @param  ?int  $totalViews
     * @param  ?int  $totalPlayTime
     * @param  ?float  $globalValue
     * @phpstan-pure
     */
    public function __construct(?float $value = null, ?int $totalWatchTime = null, ?int $uniqueViews = null, ?int $totalViews = null, ?int $totalPlayTime = null, ?float $globalValue = null)
    {
        $this->value = $value;
        $this->totalWatchTime = $totalWatchTime;
        $this->uniqueViews = $uniqueViews;
        $this->totalViews = $totalViews;
        $this->totalPlayTime = $totalPlayTime;
        $this->globalValue = $globalValue;
    }
}