<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


class MetricsBreakdownDetails
{
    /**
     * Total count of view sessions for a paricular video content.
     *
     * @var ?int $views
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('views')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?int $views = null;

    /**
     * The specific metric value calculated based on the applied filters.
     *
     * @var ?float $value
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('value')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?float $value = null;

    /**
     * Total time watched across all views, represented in milliseconds.
     *
     * @var ?int $totalWatchTime
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('totalWatchTime')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?int $totalWatchTime = null;

    /**
     * Total time spent playing the video, represented in milliseconds.
     *
     * @var ?int $totalPlayingTime
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('totalPlayingTime')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?int $totalPlayingTime = null;

    /**
     * the value of dimension or filter value on which the aggregation is to be applied.
     *
     * @var ?string $field
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('field')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $field = null;

    /**
     * @param  ?int  $views
     * @param  ?float  $value
     * @param  ?int  $totalWatchTime
     * @param  ?int  $totalPlayingTime
     * @param  ?string  $field
     * @phpstan-pure
     */
    public function __construct(?int $views = null, ?float $value = null, ?int $totalWatchTime = null, ?int $totalPlayingTime = null, ?string $field = null)
    {
        $this->views = $views;
        $this->value = $value;
        $this->totalWatchTime = $totalWatchTime;
        $this->totalPlayingTime = $totalPlayingTime;
        $this->field = $field;
    }
}
