<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


class Moderation
{
    /**
     * Defines the type of input. Possible values include video, audio, or av.
     *
     *
     *
     * @var ?CreateMediaRequestType $type
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('type')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\CreateMediaRequestType|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?CreateMediaRequestType $type = null;

    /**
     * @param  ?CreateMediaRequestType  $type
     * @phpstan-pure
     */
    public function __construct(?CreateMediaRequestType $type = null)
    {
        $this->type = $type;
    }
}