<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


class Placement
{
    /**
     * Horizontal alignment of the watermark.
     *
     * @var ?XAlign $xAlign
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('xAlign')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\XAlign|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?XAlign $xAlign = null;

    /**
     * Horizontal margin from the edge of the video.
     *
     * @var ?string $xMargin
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('xMargin')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $xMargin = null;

    /**
     * Vertical alignment of the watermark.
     *
     * @var ?YAlign $yAlign
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('yAlign')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\YAlign|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?YAlign $yAlign = null;

    /**
     * Vertical margin from the edge of the video.
     *
     * @var ?string $yMargin
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('yMargin')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $yMargin = null;

    /**
     * @param  ?XAlign  $xAlign
     * @param  ?string  $xMargin
     * @param  ?YAlign  $yAlign
     * @param  ?string  $yMargin
     * @phpstan-pure
     */
    public function __construct(?XAlign $xAlign = null, ?string $xMargin = null, ?YAlign $yAlign = null, ?string $yMargin = null)
    {
        $this->xAlign = $xAlign;
        $this->xMargin = $xMargin;
        $this->yAlign = $yAlign;
        $this->yMargin = $yMargin;
    }
}
