<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** PlaybackIdSuccessResponse - Displays the result of the request. */
class PlaybackIdSuccessResponse
{
    /**
     * Shows the request status. Returns true for success and false for failure.
     *
     * @var ?bool $success
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('success')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $success = null;

    /**
     *
     * @var ?PlaybackIdSuccessResponseData $data
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('data')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\PlaybackIdSuccessResponseData|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?PlaybackIdSuccessResponseData $data = null;

    /**
     * @param  ?bool  $success
     * @param  ?PlaybackIdSuccessResponseData  $data
     * @phpstan-pure
     */
    public function __construct(?bool $success = null, ?PlaybackIdSuccessResponseData $data = null)
    {
        $this->success = $success;
        $this->data = $data;
    }
}