<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** PlaybackSettings - Displays the result of the playback settings. */
class PlaybackSettings
{
    /**
     * Determines if access to the streamed content is kept private or available to all.
     *
     * @var ?PlaybackSettingsAccessPolicy $accessPolicy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accessPolicy')]
    #[\Speakeasy\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\PlaybackSettingsAccessPolicy|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PlaybackSettingsAccessPolicy $accessPolicy = null;

    /**
     * @param  ?PlaybackSettingsAccessPolicy  $accessPolicy
     * @phpstan-pure
     */
    public function __construct(?PlaybackSettingsAccessPolicy $accessPolicy = PlaybackSettingsAccessPolicy::Public)
    {
        $this->accessPolicy = $accessPolicy;
    }
}