<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** PlaybackIdDomains - Restrictions based on the originating domain of a request (e.g., whether requests from certain websites should be allowed or blocked). */
class PlaybackIdDomains
{
    /**
     * This sets the default behavior for domain access (either "allow" or "deny").
     *
     * @var ?PlaybackIdDomainsDefaultPolicy $defaultPolicy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('defaultPolicy')]
    #[\Speakeasy\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\PlaybackIdDomainsDefaultPolicy|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PlaybackIdDomainsDefaultPolicy $defaultPolicy = null;

    /**
     * A list of domains that are explicitly allowed access.
     *
     * @var ?array<string> $allow
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('allow')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $allow = null;

    /**
     * A list of domains that are explicitly blocked from accessing the resource.
     *
     * @var ?array<string> $deny
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deny')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $deny = null;

    /**
     * @param  ?PlaybackIdDomainsDefaultPolicy  $defaultPolicy
     * @param  ?array<string>  $allow
     * @param  ?array<string>  $deny
     * @phpstan-pure
     */
    public function __construct(?PlaybackIdDomainsDefaultPolicy $defaultPolicy = null, ?array $allow = null, ?array $deny = null)
    {
        $this->defaultPolicy = $defaultPolicy;
        $this->allow = $allow;
        $this->deny = $deny;
    }
}