<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** PlaybackIdAccessRestrictions - Controls access based on domains and user agents. Defines a default policy (either "allow" or "deny") and provides lists for explicitly allowed or denied domains and user agents. */
class PlaybackIdAccessRestrictions
{
    /**
     * Restrictions based on the originating domain of a request (e.g., whether requests from certain websites should be allowed or blocked).
     *
     * @var ?PlaybackIdDomains $domains
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('domains')]
    #[\Speakeasy\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\PlaybackIdDomains|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PlaybackIdDomains $domains = null;

    /**
     * Restrictions based on the user agent (which is typically a string sent by browsers or bots identifying themselves).
     *
     * @var ?PlaybackIdUserAgents $userAgents
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('userAgents')]
    #[\Speakeasy\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\PlaybackIdUserAgents|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PlaybackIdUserAgents $userAgents = null;

    /**
     * @param  ?PlaybackIdDomains  $domains
     * @param  ?PlaybackIdUserAgents  $userAgents
     * @phpstan-pure
     */
    public function __construct(?PlaybackIdDomains $domains = null, ?PlaybackIdUserAgents $userAgents = null)
    {
        $this->domains = $domains;
        $this->userAgents = $userAgents;
    }
}