<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** PlaybackIdResponse - Displays the result of the request. */
class PlaybackIdResponse
{
    /**
     * It demonstrates whether the request is successful or not.
     *
     * @var ?bool $success
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('success')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $success = null;

    /**
     *
     * @var ?PlaybackIdResponseData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\PlaybackIdResponseData|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PlaybackIdResponseData $data = null;

    /**
     * @param  ?bool  $success
     * @param  ?PlaybackIdResponseData  $data
     * @phpstan-pure
     */
    public function __construct(?bool $success = null, ?PlaybackIdResponseData $data = null)
    {
        $this->success = $success;
        $this->data = $data;
    }
}