<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


class PlaylistItem
{
    /**
     * The unique id of the playlist
     *
     * @var ?string $id
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('id')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * The name of the playlist set by the user
     *
     * @var ?string $name
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('name')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * type of the playlist, when it was created
     *
     * @var ?PlaylistItemType $type
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('type')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\PlaylistItemType|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?PlaylistItemType $type = null;

    /**
     * Unique string value assigned by user to the playlist.
     *
     * @var ?string $referenceId
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('referenceId')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $referenceId = null;

    /**
     * Timestamp of playlist creation.
     *
     * @var ?\DateTime $createdAt
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('createdAt')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * No. of media present in the playlist
     *
     * @var ?int $mediaCount
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('mediaCount')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?int $mediaCount = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $name
     * @param  ?PlaylistItemType  $type
     * @param  ?string  $referenceId
     * @param  ?\DateTime  $createdAt
     * @param  ?int  $mediaCount
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?string $name = null, ?PlaylistItemType $type = null, ?string $referenceId = null, ?\DateTime $createdAt = null, ?int $mediaCount = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->type = $type;
        $this->referenceId = $referenceId;
        $this->createdAt = $createdAt;
        $this->mediaCount = $mediaCount;
    }
}
