<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


class PlaylistByIdResponseDataSmart
{
    /**
     * type of the playlist, when it was created
     *
     * @var PlaylistByIdResponseDataSmartType $type
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('type')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\PlaylistByIdResponseDataSmartType')]
    public PlaylistByIdResponseDataSmartType $type;

    /**
     * Determines the insertion order of media into playlist.
     *
     * @var PlaylistOrder $playOrder
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('playOrder')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\PlaylistOrder')]
    public PlaylistOrder $playOrder;

    /**
     * Required when the playlist type is `smart`. Media created between `startDate` and `endDate` of `createdDate` is added. Optionally, you can include media based on `updatedDate`.
     *
     * @var PlaylistByIdResponseMetadata $metadata
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('metadata')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\PlaylistByIdResponseMetadata')]
    public PlaylistByIdResponseMetadata $metadata;

    /**
     * The unique id of the playlist
     *
     * @var ?string $id
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('id')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * The name of the playlist set by the user
     *
     * @var ?string $name
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('name')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * Unique string value assigned by user to the playlist.
     *
     * @var ?string $referenceId
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('referenceId')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $referenceId = null;

    /**
     * Description of the playlist set by the user.
     *
     * @var ?string $description
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('description')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * $mediaList
     *
     * @var ?array<PlaylistByIdResponseMediaListItem> $mediaList
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('mediaList')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('array<\FastPix\Sdk\Models\Components\PlaylistByIdResponseMediaListItem>|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?array $mediaList = null;

    /**
     * The unique id of the workspace in which the playlist is present.
     *
     * @var ?string $workspaceId
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('workspaceId')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $workspaceId = null;

    /**
     * Timestamp of playlist creation.
     *
     * @var ?\DateTime $createdAt
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('createdAt')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * Playlist's most recent update timestamp.
     *
     * @var ?\DateTime $updatedAt
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('updatedAt')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $updatedAt = null;

    /**
     * No. of media present in the playlist
     *
     * @var ?int $mediaCount
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('mediaCount')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?int $mediaCount = null;

    /**
     * @param  PlaylistByIdResponseDataSmartType  $type
     * @param  PlaylistOrder  $playOrder
     * @param  PlaylistByIdResponseMetadata  $metadata
     * @param  ?string  $id
     * @param  ?string  $name
     * @param  ?string  $referenceId
     * @param  ?string  $description
     * @param  ?array<PlaylistByIdResponseMediaListItem>  $mediaList
     * @param  ?string  $workspaceId
     * @param  ?\DateTime  $createdAt
     * @param  ?\DateTime  $updatedAt
     * @param  ?int  $mediaCount
     * @phpstan-pure
     */
    public function __construct(PlaylistByIdResponseDataSmartType $type, PlaylistOrder $playOrder, PlaylistByIdResponseMetadata $metadata, ?string $id = null, ?string $name = null, ?string $referenceId = null, ?string $description = null, ?array $mediaList = null, ?string $workspaceId = null, ?\DateTime $createdAt = null, ?\DateTime $updatedAt = null, ?int $mediaCount = null)
    {
        $this->type = $type;
        $this->playOrder = $playOrder;
        $this->metadata = $metadata;
        $this->id = $id;
        $this->name = $name;
        $this->referenceId = $referenceId;
        $this->description = $description;
        $this->mediaList = $mediaList;
        $this->workspaceId = $workspaceId;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->mediaCount = $mediaCount;
    }
}