<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


class PlaylistByIdResponseMediaListItem
{
    /**
     * Timestamp of media creation in the workspace.
     *
     * @var ?\DateTime $createdAt
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('createdAt')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdAt = null;

    /**
     * Duration of the media in hh:mm:ss format.
     *
     * @var ?string $duration
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('duration')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $duration = null;

    /**
     * unique id of the particular media.
     *
     * @var ?string $id
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('id')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * source resolution of the media.
     *
     * @var ?string $sourceResolution
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('sourceResolution')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $sourceResolution = null;

    /**
     * status of the media, only media with ready status is added to playlist.
     *
     * @var ?string $status
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('status')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $status = null;

    /**
     * thumbnail for the particular media.
     *
     * @var ?string $thumbnail
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('thumbnail')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $thumbnail = null;

    /**
     * Creator ID of the media.
     *
     * @var ?string $creatorId
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('creatorId')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $creatorId = null;

    /**
     * Title of the media.
     *
     * @var ?string $title
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('title')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;
}
