<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** This sets the default behavior for domain access (either "allow" or "deny"). */
enum PlaybackIdDomainsDefaultPolicy: string
{
    case Allow = 'allow';
    case Deny = 'deny';
}
