<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


class PullVideoInput
{
    /**
     * Start time indicates where encoding must begin within the video file. For example, if you want to encode a segment from 3 minutes (180 seconds) to 6 minutes (360 seconds) in a 10-minute (600 seconds) video, the start time is 3 minutes (180 seconds). Note: Start time is always mentioned in seconds.
     *
     *
     *
     * @var ?int $startTime
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('startTime')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?int $startTime = null;

    /**
     * End time indicates where encoding must end within the video file. For example, if you want to encode a segment from 3 minutes (180 seconds) to 6 minutes (360 seconds) in a 10-minute (600 seconds) video, the end time is 6 minutes (360 seconds). Note: End time is always mentioned in seconds.
     *
     *
     *
     * @var ?int $endTime
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('endTime')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?int $endTime = null;

    /**
     * The URL of the **intro video** to be added at the beginning of the media file.
     *
     * The URL must be **valid, publicly accessible, and downloadable** so that FastPix can fetch the file successfully.
     * Supported video formats include **MP4, MOV, MKV, and TS** for optimal processing performance.
     *
     *
     * @var ?string $introUrl
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('introUrl')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $introUrl = null;

    /**
     * The URL of the **outro video** to be added at the end of the media file.
     *
     * The URL must be **valid, publicly accessible, and downloadable** so that FastPix can retrieve the file successfully.
     * Supported video formats include **MP4, MOV, MKV, and TS** for best compatibility and processing speed.
     *
     *
     * @var ?string $outroUrl
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('outroUrl')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $outroUrl = null;

    /**
     * The list of start and end times (in seconds) of the segments to be removed from the actual video.
     *
     *
     *
     * @var ?array<string> $expungeSegments
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('expungeSegments')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('array<string>|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?array $expungeSegments = null;

    /**
     * A list of media segments to be added or processed. Each segment includes details such as the URL of the media file and instructions on where it should be inserted in the final media composition. A segment can either specify an exact timestamp  (`insertAt`) or indicate that it must be added at the end (`insertAtEnd`).
     *
     * @var ?array<PullVideoInputSegment1|PullVideoInputSegment2> $segments
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('segments')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('array<\FastPix\Sdk\Models\Components\PullVideoInputSegment1|\FastPix\Sdk\Models\Components\PullVideoInputSegment2>|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?array $segments = null;

    /**
     * Defines the type of input.
     *
     *
     *
     * @var ?string $type
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('type')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $type = null;

    /**
     * The URL hosts the media file for FastPix, which needs to be downloaded to use further. It supports formats like MP3, MP4, MOV, MKV, or TS, and includes text tracks for subtitles or closed captions (SRT/VTT files). The URL must be valid, publicly accessible, and downloadable to ensure FastPix can fetch the file successfully.
     *
     *
     * While FastPix can handle various audio and video formats and codecs, using standard and widely supported formats helps achieve optimal processing speed.
     *
     *
     * @var ?string $url
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('url')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $url = null;

    /**
     * @param  ?string  $type
     * @param  ?string  $url
     * @param  ?int  $startTime
     * @param  ?int  $endTime
     * @param  ?string  $introUrl
     * @param  ?string  $outroUrl
     * @param  ?array<string>  $expungeSegments
     * @param  ?array<PullVideoInputSegment1|PullVideoInputSegment2>  $segments
     * @phpstan-pure
     */
    public function __construct(?int $startTime = null, ?int $endTime = null, ?string $introUrl = null, ?string $outroUrl = null, ?array $expungeSegments = null, ?array $segments = null, ?string $type = 'video', ?string $url = 'https://static.fastpix.com/fp-sample-video.mp4') // NOSONAR php:S107 - generated request DTO; params mirror the API schema and must stay for named-arg construction
    {
        $this->startTime = $startTime;
        $this->endTime = $endTime;
        $this->introUrl = $introUrl;
        $this->outroUrl = $outroUrl;
        $this->expungeSegments = $expungeSegments;
        $this->segments = $segments;
        $this->type = $type;
        $this->url = $url;
    }
}
