<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;

use FastPix\Sdk\Utils\SdkMetadata;
class Security
{
    /**
     *
     * @var string $username
     */
    #[SdkMetadata('security:scheme=true,type=http,subtype=basic,name=username')]
    public string $username;

    /**
     *
     * @var string $password
     */
    #[SdkMetadata('security:scheme=true,type=http,subtype=basic,name=password')]
    public string $password;

    /**
     * @param  string  $username
     * @param  string  $password
     * @phpstan-pure
     */
    public function __construct(string $username, string $password)
    {
        $this->username = $username;
        $this->password = $password;
    }
}
