<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/**
 * SourceAccessMediaMp4Support - Details of an MP4 rendition generated for the media.
 *
 * Each entry describes a single MP4 rendition, for example a `capped_4k` video
 * rendition or an `audioOnly` rendition. Audio-only renditions have no height or width.
 *
 */
class SourceAccessMediaMp4Support
{
    /**
     * The MP4 rendition type. `capped_4k` is a downloadable MP4 video capped at 4K resolution, `audioOnly` is a downloadable m4a audio-only file.
     *
     * @var ?SourceAccessMediaMp4SupportType $type
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('type')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\SourceAccessMediaMp4SupportType|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?SourceAccessMediaMp4SupportType $type = null;

    /**
     * Generation status of this MP4 rendition.
     *
     * @var ?SourceAccessMediaMp4SupportStatus $status
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('status')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\SourceAccessMediaMp4SupportStatus|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?SourceAccessMediaMp4SupportStatus $status = null;

    /**
     * Pixel height of the rendition. Omitted for the `audioOnly` type.
     *
     * @var ?int $height
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('height')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?int $height = null;

    /**
     * Pixel width of the rendition. Omitted for the `audioOnly` type.
     *
     * @var ?int $width
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('width')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?int $width = null;

    /**
     * File extension of the downloadable rendition.
     *
     * @var ?SourceAccessMediaMp4SupportExt $ext
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('ext')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\SourceAccessMediaMp4SupportExt|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?SourceAccessMediaMp4SupportExt $ext = null;

    /**
     * @param  ?SourceAccessMediaMp4SupportType  $type
     * @param  ?SourceAccessMediaMp4SupportStatus  $status
     * @param  ?int  $height
     * @param  ?int  $width
     * @param  ?SourceAccessMediaMp4SupportExt  $ext
     * @phpstan-pure
     */
    public function __construct(?SourceAccessMediaMp4SupportType $type = null, ?SourceAccessMediaMp4SupportStatus $status = null, ?int $height = null, ?int $width = null, ?SourceAccessMediaMp4SupportExt $ext = null)
    {
        $this->type = $type;
        $this->status = $status;
        $this->height = $height;
        $this->width = $width;
        $this->ext = $ext;
    }
}
