<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** SubtitleTrack - A media consists of different media tracks, like video, audio, and subtitle, all combined. */
class SubtitleTrack
{
    /**
     * FastPix generates a unique identifier for each track.
     *
     * @var ?string $id
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('id')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Defines the type of input track.
     *
     * @var ?SubtitleTrackType $type
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('type')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\SubtitleTrackType|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?SubtitleTrackType $type = null;

    /**
     * Indicates the current state of the track. 'available' means the track has been processed successfully and is ready to be used or played.
     *
     * @var ?string $status
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('status')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $status = null;

    /**
     * Name of the language in which the subtitles will be generated.
     *
     *
     *
     * @var ?string $languageName
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('languageName')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $languageName = null;

    /**
     * Language codes are concise, standardized symbols that denote languages, utilizing either two or three characters for identification. The language code must be compliant with the BCP 47 standard to ensure compatibility. (for text only).
     *
     *
     *
     * @var ?string $languageCode
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('languageCode')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $languageCode = null;

    /**
     * @param  ?string  $id
     * @param  ?SubtitleTrackType  $type
     * @param  ?string  $status
     * @param  ?string  $languageName
     * @param  ?string  $languageCode
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?SubtitleTrackType $type = null, ?string $status = null, ?string $languageName = null, ?string $languageCode = null)
    {
        $this->id = $id;
        $this->type = $type;
        $this->status = $status;
        $this->languageName = $languageName;
        $this->languageCode = $languageCode;
    }
}