<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** SubtitleInput - Generates subtitle files for audio/video files. */
class SubtitleInput
{
    /**
     * Defines the type of input.
     *
     *
     *
     * @var string $type
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * The direct URL of the subtitle file.
     *
     * @var string $url
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     * Name of the language in which the subtitles will be generated.
     *
     * @var string $languageName
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('languageName')]
    public string $languageName;

    /**
     * Language code for content localization
     *
     * @var ?LanguageCode $languageCode
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('languageCode')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\LanguageCode|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?LanguageCode $languageCode = null;

    /**
     * @param  string  $type
     * @param  string  $url
     * @param  string  $languageName
     * @param  ?LanguageCode  $languageCode
     * @phpstan-pure
     */
    public function __construct(string $type, string $url, string $languageName, ?LanguageCode $languageCode = LanguageCode::EnUS)
    {
        $this->type = $type;
        $this->url = $url;
        $this->languageName = $languageName;
        $this->languageCode = $languageCode;
    }
}