<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** UnusedUploadsPlaybackIdAccessRestrictions - Controls access based on domains and user agents. Defines a default policy (either "allow" or "deny") and provides lists for explicitly allowed or denied domains and user agents. */
class UnusedUploadsPlaybackIdAccessRestrictions
{
    /**
     * Restrictions based on the originating domain of a request (for example, whether requests from certain websites must be allowed or blocked).
     *
     * @var ?UnusedUploadsPlaybackIdDomains $domains
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('domains')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\UnusedUploadsPlaybackIdDomains|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?UnusedUploadsPlaybackIdDomains $domains = null;

    /**
     * Restrictions based on the user agent (which is typically a string sent by browsers or bots identifying themselves).
     *
     * @var ?UnusedUploadsPlaybackIdUserAgents $userAgents
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('userAgents')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\UnusedUploadsPlaybackIdUserAgents|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?UnusedUploadsPlaybackIdUserAgents $userAgents = null;

    /**
     * @param  ?UnusedUploadsPlaybackIdDomains  $domains
     * @param  ?UnusedUploadsPlaybackIdUserAgents  $userAgents
     * @phpstan-pure
     */
    public function __construct(?UnusedUploadsPlaybackIdDomains $domains = null, ?UnusedUploadsPlaybackIdUserAgents $userAgents = null)
    {
        $this->domains = $domains;
        $this->userAgents = $userAgents;
    }
}
