<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


class UnusedDirectUploadResponse
{
    /**
     * $playbackIds
     *
     * @var ?array<UnusedUploadsPlaybackId> $playbackIds
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('playbackIds')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('array<\FastPix\Sdk\Models\Components\UnusedUploadsPlaybackId>|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?array $playbackIds = null;

    /**
     * You can search for videos with specific key value pairs using metadata, when you tag a video in "key" : "value" pairs. Dynamic metadata allows you to define a key that allows any value pair. You can have maximum of 255 characters and upto 10 entries are allowed.
     *
     *
     *
     * @var ?array<string, string> $metadata
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('metadata')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('array<string, string>|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * The quality tier applied to the media.
     *
     * @var ?UnusedDirectUploadResponseMediaQuality $mediaQuality
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('mediaQuality')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\UnusedDirectUploadResponseMediaQuality|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?UnusedDirectUploadResponseMediaQuality $mediaQuality = null;

    /**
     * The sourceAccess parameter determines whether the original media file is accessible. Set to true to enable access or false to restrict it.
     *
     *
     *
     * @var ?bool $sourceAccess
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('sourceAccess')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $sourceAccess = null;

    /**
     * Enhance the quality and volume of the audio track. This is available for pre-recorded content only.
     *
     *
     *
     * @var ?bool $optimizeAudio
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('optimizeAudio')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $optimizeAudio = null;

    /**
     * @param  ?array<UnusedUploadsPlaybackId>  $playbackIds
     * @param  ?array<string, string>  $metadata
     * @param  ?UnusedDirectUploadResponseMediaQuality  $mediaQuality
     * @param  ?bool  $sourceAccess
     * @param  ?bool  $optimizeAudio
     * @phpstan-pure
     */
    public function __construct(?array $playbackIds = null, ?array $metadata = null, ?UnusedDirectUploadResponseMediaQuality $mediaQuality = null, ?bool $sourceAccess = null, ?bool $optimizeAudio = null)
    {
        $this->playbackIds = $playbackIds;
        $this->metadata = $metadata;
        $this->mediaQuality = $mediaQuality;
        $this->sourceAccess = $sourceAccess;
        $this->optimizeAudio = $optimizeAudio;
    }
}
