<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** VideoTrackForGetAll - A media consists of different media tracks, like video, audio, and subtitle, all combined. */
class VideoTrackForGetAll
{
    /**
     * FastPix generates a unique identifier for each track.
     *
     * @var ?string $id
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('id')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Defines the type of input. This option is mandatory.
     *
     * @var ?string $type
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('type')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $type = null;

    /**
     * Track width denotes the range of widths applicable to a specific track. Currently, this setting can be modified only for video tracks
     *
     * @var ?float $width
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('width')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?float $width = null;

    /**
     * Track height denotes the range of height applicable to a specific track. Currently, this setting can be modified only for video tracks.
     *
     * @var ?float $height
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('height')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?float $height = null;

    /**
     * Indicates the current state of the track. 'available' means the track has been processed successfully and is ready to be used or played.
     *
     * @var ?string $status
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('status')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $status = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $type
     * @param  ?float  $width
     * @param  ?float  $height
     * @param  ?string  $status
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?string $type = null, ?float $width = null, ?float $height = null, ?string $status = null)
    {
        $this->id = $id;
        $this->type = $type;
        $this->width = $width;
        $this->height = $height;
        $this->status = $status;
    }
}