<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


class ViewsList
{
    /**
     * The unique identifier for the viewing session of the user.
     *
     *
     *
     * @var ?string $viewId
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('viewId')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $viewId = null;

    /**
     * Operating System signifies the software platform utilized by the viewer
     *
     *
     *
     * @var ?string $operatingSystem
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('operatingSystem')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $operatingSystem = null;

    /**
     * The browser name of the viewer.
     *
     *
     *
     * @var ?string $application
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('application')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $application = null;

    /**
     * The start timestamp of the video view.
     *
     *
     *
     * @var ?string $viewStartTime
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('viewStartTime')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $viewStartTime = null;

    /**
     * The end timestamp of the video view.
     *
     *
     *
     * @var ?string $viewEndTime
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('viewEndTime')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $viewEndTime = null;

    /**
     * The title of the Video.
     *
     *
     *
     * @var ?string $videoTitle
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('videoTitle')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $videoTitle = null;

    /**
     * The code which represents specific issues or failures that occur during playback. These can be implementation specific.
     *
     *
     *
     * @var ?string $errorCode
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('errorCode')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $errorCode = null;

    /**
     * The notifications or messages that inform users or developers about issues or failures that have occurred during the playback representing error codes.
     *
     *
     *
     * @var ?string $errorMessage
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('errorMessage')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $errorMessage = null;

    /**
     * The unique identifier for the error that occurred during playback.
     *
     *
     *
     * @var ?string $errorId
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('errorId')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $errorId = null;

    /**
     * Country of the viewer.
     *
     *
     *
     * @var ?string $country
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('country')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $country = null;

    /**
     * The watch time represents the time spent watching the video including staruptime, playback time ,buffering time.
     *
     *
     *
     * @var ?float $viewWatchTime
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('viewWatchTime')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?float $viewWatchTime = null;

    /**
     * The viewer experience encapsulated in the form of score while watching the video.
     *
     *
     *
     * @var ?float $qoeScore
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('QoeScore')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?float $qoeScore = null;
}
