<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


class ViewsCountResponse
{
    /**
     * Shows the request status. Returns true for success and false for failure.
     *
     * @var ?bool $success
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('success')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?bool $success = null;

    /**
     * Contains the view count details.
     *
     * @var ?ViewsCountResponseData $data
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('data')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\ViewsCountResponseData|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?ViewsCountResponseData $data = null;

    /**
     * @param  ?bool  $success
     * @param  ?ViewsCountResponseData  $data
     * @phpstan-pure
     */
    public function __construct(?bool $success = null, ?ViewsCountResponseData $data = null)
    {
        $this->success = $success;
        $this->data = $data;
    }
}
