<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/**
 * WatermarkInput - Contains configuration details for applying a watermark overlay to a video.
 *
 * The watermark is placed over the media content during processing.
 * For detailed setup steps and customization options, refer to the
 * <a href="https://fastpix.com/docs/edit-and-transform-videos/add-a-watermark-to-a-video" target="_blank">FastPix Watermark Guide</a>.
 *
 */
class WatermarkInput
{
    /**
     * Type of overlay (currently only supports "watermark").
     *
     * @var WatermarkInputType $type
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('type')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\WatermarkInputType')]
    public WatermarkInputType $type;

    /**
     * URL of the watermark image.
     *
     * @var string $url
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     *
     * @var ?Placement $placement
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('placement')]
    #[\FastPix\Sdk\Serializer\Annotation\Type('\FastPix\Sdk\Models\Components\Placement|null')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?Placement $placement = null;

    /**
     * Width of the watermark in percentage or pixels.
     *
     * @var ?string $width
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('width')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $width = null;

    /**
     * Height of the watermark in percentage or pixels.
     *
     * @var ?string $height
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('height')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $height = null;

    /**
     * Opacity of the watermark in percentage.
     *
     * @var ?string $opacity
     */
    #[\FastPix\Sdk\Serializer\Annotation\SerializedName('opacity')]
    #[\FastPix\Sdk\Serializer\Annotation\SkipWhenNull]
    public ?string $opacity = null;

    /**
     * @param  WatermarkInputType  $type
     * @param  string  $url
     * @param  ?Placement  $placement
     * @param  ?string  $width
     * @param  ?string  $height
     * @param  ?string  $opacity
     * @phpstan-pure
     */
    public function __construct(WatermarkInputType $type, string $url, ?Placement $placement = null, ?string $width = null, ?string $height = null, ?string $opacity = null)
    {
        $this->type = $type;
        $this->url = $url;
        $this->placement = $placement;
        $this->width = $width;
        $this->height = $height;
        $this->opacity = $opacity;
    }
}
