<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** Vertical alignment of the watermark. */
enum YAlign: string
{
    case Top = 'top';
    case Middle = 'middle';
    case Bottom = 'bottom';
}
