<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace FastPix\Sdk\Models\Components;


/** Vertical alignment of the watermark. */
enum YAlign: string
{
    case Top = 'top';
    case Middle = 'middle';
    case Bottom = 'bottom';
}
