<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk;

use FastPix\Sdk\Hooks\HookContext;
use FastPix\Sdk\Models\Operations;
use FastPix\Sdk\Serializer\DeserializationContext;

class Errors
{
    private const CONTENT_TYPE_JSON = 'application/json';

    private const ERROR_API = 'API error occurred';

    private const ERROR_UNKNOWN_CONTENT_TYPE = 'Unknown content type received';

    private SDKConfiguration $sdkConfiguration;
    /**
     * @param  SDKConfiguration  $sdkConfig
     */
    public function __construct(public SDKConfiguration $sdkConfig)
    {
        $this->sdkConfiguration = $sdkConfig;
    }
    /**
     * @param  string  $baseUrl
     * @param  array<string, string>  $urlVariables
     *
     * @return string
     */
    public function getUrl(string $baseUrl, array $urlVariables): string
    {
        $serverDetails = $this->sdkConfiguration->getServerDetails();

        if ($baseUrl == null) {
            $baseUrl = $serverDetails->baseUrl;
        }

        if ($urlVariables == null) {
            $urlVariables = $serverDetails->options;
        }

        return Utils\Utils::templateUrl($baseUrl, $urlVariables);
    }

    /**
     * List errors
     *
     * This endpoint returns the total number of playback errors that occurred, along with the total number of views captured, based on the specified timespan and filters. It provides insights into the overall playback quality and helps identify potential issues that may impact viewer experience.
     *
     *
     * #### Key fields in response
     *
     * * **percentage:** The percentage of views affected by the specific error.
     * * **uniqueViewersEffectedPercentage:** The percentage of unique viewers affected by the specific error (available only in the topErrors section).
     * * **notes:** Additional notes or information about the specific error.
     * * **message:** The error message or description.
     * * **lastSeen:** The timestamp of when the error was last observed.
     * * **id:** The unique identifier for the specific error.
     * * **description:** A description of the specific error.
     * * **count:** The number of occurrences of the specific error.
     * * **code:** The error code associated with the specific error.
     *
     *
     * Related guide: <a href="https://fastpix.com/docs/video-data/troubleshoot-playback-errors">Troubleshoot errors</a>
     *
     *
     * @param  ?Operations\ListErrorsTimespan  $timespan
     * @param  ?string  $filterby
     * @param  ?int  $limit
     * @return Operations\ListErrorsResponse
     * @throws \FastPix\Sdk\Models\Errors\APIException
     */
    public function listErrors(?Operations\ListErrorsTimespan $timespan = null, ?string $filterby = null, ?int $limit = null): Operations\ListErrorsResponse
    {
        $request = new Operations\ListErrorsRequest(
            timespan: $timespan,
            filterby: $filterby,
            limit: $limit,
        );
        $baseUrl = $this->sdkConfiguration->getTemplatedServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/data/errors');
        $urlOverride = null;
        $httpOptions = ['http_errors' => false];

        $qp = Utils\Utils::getQueryParams(Operations\ListErrorsRequest::class, $request, $urlOverride);
        $httpOptions['headers']['Accept'] = self::CONTENT_TYPE_JSON;
        $httpOptions['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        $httpRequest = new \GuzzleHttp\Psr7\Request('GET', $url);
        $hookContext = new HookContext($this->sdkConfiguration, $baseUrl, 'list_errors', null, $this->sdkConfiguration->securitySource);
        $httpRequest = $this->sdkConfiguration->hooks->beforeRequest(new Hooks\BeforeRequestContext($hookContext), $httpRequest);
        $httpOptions['query'] = Utils\QueryParameters::standardizeQueryParams($httpRequest, $qp);
        $httpOptions = Utils\Utils::convertHeadersToOptions($httpRequest, $httpOptions);
        $httpRequest = Utils\Utils::removeHeaders($httpRequest);
        try {
            $httpResponse = $this->sdkConfiguration->client->send($httpRequest, $httpOptions);
        } catch (\GuzzleHttp\Exception\GuzzleException $error) {
            $res = $this->sdkConfiguration->hooks->afterError(new Hooks\AfterErrorContext($hookContext), null, $error);
            $httpResponse = $res;
        }
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $statusCode = $httpResponse->getStatusCode();
        if (Utils\Utils::matchStatusCodes($statusCode, ['4XX', '5XX'])) {
            $res = $this->sdkConfiguration->hooks->afterError(new Hooks\AfterErrorContext($hookContext), $httpResponse, null);
            $httpResponse = $res;
        }
        if (Utils\Utils::matchStatusCodes($statusCode, ['200'])) {
            return $this->buildListErrorsResponse($statusCode, $contentType, $httpResponse, $hookContext, '\FastPix\Sdk\Models\Operations\ListErrorsResponseBody', false);
        }
        if (Utils\Utils::matchStatusCodes($statusCode, ['4XX', '5XX'])) {
            throw new \FastPix\Sdk\Models\Errors\APIException(self::ERROR_API, $statusCode, $httpResponse->getBody()->getContents(), $httpResponse);
        }

        return $this->buildListErrorsResponse($statusCode, $contentType, $httpResponse, $hookContext, '\FastPix\Sdk\Models\Components\DefaultError', true);
    }

    /**
     * Deserializes a JSON response body and builds the operation response, throwing on a non-JSON content type.
     *
     * @param  string  $bodyClass
     * @return Operations\ListErrorsResponse
     *
     * @throws \FastPix\Sdk\Models\Errors\APIException
     */
    private function buildListErrorsResponse(int $statusCode, string $contentType, \Psr\Http\Message\ResponseInterface $httpResponse, HookContext $hookContext, string $bodyClass, bool $asError): Operations\ListErrorsResponse
    {
        if (! Utils\Utils::matchContentType($contentType, self::CONTENT_TYPE_JSON)) {
            throw new \FastPix\Sdk\Models\Errors\APIException(self::ERROR_UNKNOWN_CONTENT_TYPE, $statusCode, $httpResponse->getBody()->getContents(), $httpResponse);
        }

        $httpResponse = $this->sdkConfiguration->hooks->afterSuccess(new Hooks\AfterSuccessContext($hookContext), $httpResponse);
        $serializer = Utils\JSON::createSerializer();
        $responseData = (string) $httpResponse->getBody();
        $obj = $serializer->deserialize($responseData, $bodyClass, 'json', DeserializationContext::create()->setRequireAllRequiredProperties(true));

        return new Operations\ListErrorsResponse(
            statusCode: $statusCode,
            contentType: $contentType,
            rawResponse: $httpResponse,
            object: $asError ? null : $obj,
            defaultError: $asError ? $obj : null,
        );
    }

}
