<?php

/*
* This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

declare(strict_types=1);

namespace FastPix\Sdk;

use FastPix\Sdk\Utils\Retry;

/**
 * FastpixsdkBuilder is used to configure and build an instance of the SDK.
 */
class FastpixsdkBuilder
{
    public function __construct(
        private SDKConfiguration $sdkConfig = new SDKConfiguration(),
    ) {
    }

    /**
     * setClient allows setting a custom Guzzle client for the SDK to make requests with.
     *
     * @param  \GuzzleHttp\ClientInterface  $client
     * @return FastpixsdkBuilder
     */
    public function setClient(\GuzzleHttp\ClientInterface $client): FastpixsdkBuilder
    {
        $this->sdkConfig->client = $client;

        return $this;
    }

    /**
     * setSecurity is used to configure the security required for the SDK.
     *
     * @param  Models\Components\Security  $security
     * @return FastpixsdkBuilder
     */
    public function setSecurity(Models\Components\Security $security): FastpixsdkBuilder
    {
        $this->sdkConfig->securitySource = fn () => $security;

        return $this;
    }

    /**
     * setSecuritySource is usd to configure the security required for the SDK.
     * unlike setSecurity, setSecuritySource accepts a closure that will be called to retrieve the security information.
     *
     * @param  pure-Closure(): Models\Components\Security  $securitySource
     * @return FastpixsdkBuilder
     */
    public function setSecuritySource(\Closure $securitySource): FastpixsdkBuilder
    {
        $this->sdkConfig->securitySource = $securitySource;

        return $this;
    }

    /**
     * setServerUrl is used to configure the server URL for the SDK, and optionally template any parameters in the URL.
     *
     * @param  string  $serverUrl
     * @param  array<string, string>  $params
     * @return FastpixsdkBuilder
     */
    public function setServerUrl(string $serverUrl, ?array $params = null): FastpixsdkBuilder
    {
        $this->sdkConfig->serverUrl = Utils\Utils::templateUrl($serverUrl, $params);

        return $this;
    }

    /**
     * setServer is used to configure the server for the SDK
     *
     * @param  int  $serverIdx
     * @return FastpixsdkBuilder
     */
    public function setServerIndex(int $serverIdx): FastpixsdkBuilder
    {
        $this->sdkConfig->serverIndex = $serverIdx;

        return $this;
    }

    public function setRetryConfig(Retry\RetryConfig $config): FastpixsdkBuilder
    {
        $this->sdkConfig->retryConfig = $config;

        return $this;
    }

    /**
     * build is used to build the SDK with any of the configured options.
     *
     * @return Fastpixsdk
     */
    public function build(): Fastpixsdk
    {
        if ($this->sdkConfig->client === null) {
            $this->sdkConfig->client = new \GuzzleHttp\Client([
                'timeout' => 60,
            ]);
        }
        if ($this->sdkConfig->hasSecurity()) {
            $this->sdkConfig->client = Utils\Utils::configureSecurityClient($this->sdkConfig->client, $this->sdkConfig->getSecurity());
        }

        return new Fastpixsdk($this->sdkConfig);
    }
}